version: "2.1"

# WINDOWS: Windows REQUIRES explicit path for volumes, Linux/Mac can use relative (default).
  # Windows example cmd for startup: 
  # ROOT_PATH='c:/Users/MyName/Documents/Github/DS3' docker-compose up -d

services:
  db:
    build: 
      context: ../ds3-private01
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    labels:
      - "traefik.enable=false"

  baseimage:
    build: .
    image: 484964515519.dkr.ecr.us-east-1.amazonaws.com/baseimage
    command: bash -c 'yum list installed | grep -e php56 -e mcrypt -e pdf -e httpd24'
    labels:
      - "traefik.enable=false"

  loader:
    build:
      context: ..
      dockerfile: ds3-private01/Dockerfile
      args:
        LEGACY_DIR: ds3-private01
        LOADER_DIR: ds3-private02
        API_DIR: ds3-private03
    image: 484964515519.dkr.ecr.us-east-1.amazonaws.com/loader
    env_file: ../ds3-private02/.env.example
    environment:
      APP_URL: "https://loader.docker.localhost/"
      API_URL: "https://api.docker.localhost/"
      LEGACY_PATH: /opt/rh/httpd24/root/var/www/html/legacy
      API_PATH: /opt/rh/httpd24/root/var/www/html/api
      PHP_PATH: /opt/rh/rh-php56/root/bin/php
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    volumes:
      - "${ROOT_PATH:-..}/ds3-private01:/opt/rh/httpd24/root/var/www/html/legacy"
      - "${ROOT_PATH:-..}/ds3-private02:/opt/rh/httpd24/root/var/www/html/loader"
      - "${ROOT_PATH:-..}/ds3-private03:/opt/rh/httpd24/root/var/www/html/api"
    labels:
      - "traefik.port=80"
      - "traefik.backend=loader"
      - "traefik.frontend.rule=HostRegexp:{host:loader.docker.localhost}"

  api:
    build: ../ds3-private03
    image: 484964515519.dkr.ecr.us-east-1.amazonaws.com/api
    env_file: ../ds3-private03/.env.example
    environment:
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    volumes:
      - "${ROOT_PATH:-..}/ds3-private03:/opt/rh/httpd24/root/var/www/html/api"
    labels:
      - "traefik.port=80"
      - "traefik.backend=api"
      - "traefik.frontend.rule=HostRegexp:{host:api.docker.localhost}"

  vue:
    build: ../ds3-private06-Vue
    image: 484964515519.dkr.ecr.us-east-1.amazonaws.com/vue
    environment:
      NODE_ENV: development
      PORT: 80
    volumes:
      - "${ROOT_PATH:-..}/ds3-private06-Vue:/opt/app"
    labels:
      - "traefik.port=80"
      - "traefik.backend=vue"
      - "traefik.frontend.rule=HostRegexp:{host:vue.docker.localhost}"
 
  acceptance:
    build:
      context: ..
      dockerfile: ds3-private08-acceptance/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 80
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    command: tail -f /dev/null
    volumes:
      - "${ROOT_PATH:-..}/ds3-private08-acceptance:/opt/app/acceptance"
    labels:
      - "traefik.port=80"
      - "traefik.backend=acceptance"
      - "traefik.frontend.rule=HostRegexp:{host:acceptance.docker.localhost}"

  balancer:
    image: traefik:v1.2.3-alpine
    command: --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      # NOTE: On Windows10, Skype CONFLICTS with 443 port.
      # Either change to other port (e.g. 4433:443), or kill Skype before starting container.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./ssl/:/etc/ssl/
    labels:
      - "traefik.enable=false"

  # Available at localhost:8080 with UN/PW from DB container above
  # Consider removing this after final deploy pipeline is setup
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    links:
      - db