# A custom mysql server image to provide a database with a preloaded data
FROM mysql:5.6

# Load database Schema and Seed files to MySQL
COPY db_dev_SCHEMA_170607-2025.sql.gz /docker-entrypoint-initdb.d/0000-dump.sql.gz
COPY db_dev_SEED_170607-2025.sql.gz /docker-entrypoint-initdb.d/0001-dump.sql.gz
# COPY sql_updates/ /docker-entrypoint-initdb.d/

RUN set -x \
    && echo '[mysqld]' > /etc/mysql/conf.d/custom.cnf \
&& echo 'sql-mode="NO_ENGINE_SUBSTITUTION"' >> /etc/mysql/conf.d/custom.cnf