<?php

namespace DentalSleepSolutions\Helpers\SummaryLetterTriggers;

use DentalSleepSolutions\Structs\SummaryLetterTriggerData;

class RefusedTreatmentTrigger extends AbstractSummaryCompletedTrigger
{
    public function triggerLetter(SummaryLetterTriggerData $data): void
    {
        parent::triggerLetter($data); // TODO: Change the autogenerated stub
    }
}
