<?php

namespace DentalSleepSolutions\Http\Requests;

class UserStore extends Request
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'user_access'             => 'required|integer',
            'docid'                   => 'required|integer',
            'username'                => 'required|string',
            'npi'                     => 'regex:/^[0-9]+$/',
            'password'                => 'required|string',
            'name'                    => 'string',
            'email'                   => 'required|email',
            'address'                 => 'string',
            'city'                    => 'string',
            'state'                   => 'string',
            'zip'                     => 'regex:/^[0-9]{5}$/',
            'phone'                   => 'regex:/^[0-9]{10}$/',
            'status'                  => 'integer',
            'medicare_npi'            => 'regex:/^[0-9]+$/',
            'tax_id_or_ssn'           => 'string',
            'producer'                => 'integer',
            'practice'                => 'string',
            'email_header'            => ['regex:/^dss_email_header_[0-9]{6}_[0-9]{4}\.(gif|png|bmp|jpg|jpeg)$/'],
            'email_footer'            => ['regex:/^dss_email_footer_[0-9]{6}_[0-9]{4}\.(gif|png|bmp|jpg|jpeg)$/'],
            'fax_header'              => ['regex:/^dss_print_header_[0-9]{6}_[0-9]{4}\.(gif|png|bmp|jpg|jpeg)$/'],
            'fax_footer'              => ['regex:/^dss_print_footer_[0-9]{6}_[0-9]{4}\.(gif|png|bmp|jpg|jpeg)$/'],
            'salt'                    => 'required|string',
            'recover_hash'            => 'string',
            'recover_time'            => 'date',
            'ssn'                     => 'boolean',
            'ein'                     => 'boolean',
            'use_patient_portal'      => 'boolean',
            'mailing_practice'        => 'string',
            'mailing_name'            => 'string',
            'mailing_address'         => 'string',
            'mailing_city'            => 'string',
            'mailing_state'           => 'string',
            'mailing_zip'             => 'regex:/^[0-9]{5}$/',
            'mailing_phone'           => 'regex:/^[0-9]{10}$/',
            'last_accessed_date'      => 'date',
            'use_digital_fax'         => 'boolean',
            'fax'                     => 'string',
            'use_letters'             => 'boolean',
            'sign_notes'              => 'integer',
            'use_eligible_api'        => 'boolean',
            'access_code'             => 'string',
            'text_date'               => 'date',
            'text_num'                => 'integer',
            'access_code_date'        => 'date',
            'registration_email_date' => 'date',
            'producer_files'          => 'boolean',
            'medicare_ptan'           => 'string',
            'use_course'              => 'boolean',
            'use_course_staff'        => 'boolean',
            'manage_staff'            => 'boolean',
            'cc_id'                   => 'regex:/^cus_[A-Za-z0-9_]+$/',
            'user_type'               => 'required|integer',
            'letter_margin_header'    => 'integer',
            'letter_margin_footer'    => 'integer',
            'letter_margin_top'       => 'integer',
            'letter_margin_bottom'    => 'integer',
            'letter_margin_left'      => 'integer',
            'letter_margin_right'     => 'integer',
            'claim_margin_top'        => 'integer',
            'claim_margin_left'       => 'integer',
            'logo'                    => ['regex:/^user_logo_[0-9]+\.(gif|png|bmp|jpg|jpeg)$/'],
            'homepage'                => 'boolean',
            'use_letter_header'       => 'boolean',
            'access_code_id'          => 'integer',
            'first_name'              => 'required|string',
            'last_name'               => 'required|string',
            'indent_address'          => 'boolean',
            'registration_date'       => 'date',
            'header_space'            => 'integer',
            'billing_company_id'      => 'integer',
            'edx_id'                  => 'required|integer',
            'help_id'                 => 'integer',
            'tracker_letters'         => 'integer',
            'intro_letters'           => 'integer',
            'plan_id'                 => 'integer',
            'suspended_reason'        => 'string',
            'suspended_date'          => 'date',
            'signature_file'          => 'string',
            'signature_json'          => 'string',
            'use_service_npi'         => 'integer',
            'service_name'            => 'string',
            'service_address'         => 'string',
            'service_city'            => 'string',
            'service_state'           => 'string',
            'service_zip'             => 'regex:/^[0-9]{5}$/',
            'service_phone'           => 'regex:/^[0-9]{10}$/',
            'service_fax'             => 'regex:/^[0-9]{10}$/',
            'service_npi'             => 'string',
            'service_medicare_npi'    => 'string',
            'service_medicare_ptan'   => 'string',
            'service_tax_id_or_ssn'   => 'string',
            'service_ssn'             => 'integer',
            'service_ein'             => 'integer',
            'eligible_test'           => 'integer',
            'billing_plan_id'         => 'integer',
            'post_ledger_adjustments' => 'integer',
            'edit_ledger_entries'     => 'integer',
            'use_payment_reports'     => 'integer'
        ];
    }
}
