<?php

namespace DentalSleepSolutions\StaticClasses;

use DentalSleepSolutions\Eloquent;
use DentalSleepSolutions\Contracts\Repositories;
use DentalSleepSolutions\Contracts\Resources;
use DentalSleepSolutions\Structs\Bindings;
use DentalSleepSolutions\Http\Controllers;
use DentalSleepSolutions\Http\Requests;

class BindingSetter
{
    const MODEL_KEY = 0;
    const CONTROLLER_KEY = 1;
    const RESOURCE_KEY = 2;
    const REPOSITORY_KEY = 3;
    const REQUEST_KEY = 4;

    const EXTERNAL_MODEL_KEY = 0;
    const EXTERNAL_RESOURCE_KEY = 1;
    const EXTERNAL_REPOSITORY_KEY = 2;

    // TODO: this mega-constant should be replaced by a naming convention and reflection API
    const BINDINGS = [
        [
            Eloquent\Dental\AccessCode::class,
            Controllers\AccessCodesController::class,
            Resources\AccessCode::class,
            Repositories\AccessCodes::class,
            Requests\AccessCode::class,
        ],
        [
            Eloquent\Admin::class,
            Controllers\AdminsController::class,
            Resources\Admin::class,
            Repositories\Admins::class,
            Requests\Admin::class,
        ],
        [
            Eloquent\Dental\AirwayEvaluation::class,
            Controllers\AirwayEvaluationsController::class,
            Resources\AirwayEvaluation::class,
            Repositories\AirwayEvaluations::class,
            Requests\AirwayEvaluation::class,
        ],
        [
            Eloquent\Dental\Allergen::class,
            Controllers\AllergensController::class,
            Resources\Allergen::class,
            Repositories\Allergens::class,
            Requests\Allergen::class,
        ],
        [
            Eloquent\Dental\AppointmentType::class,
            Controllers\AppointmentTypesController::class,
            Resources\AppointmentType::class,
            Repositories\AppointmentTypes::class,
            Requests\AppointmentType::class,
        ],
        [
            Eloquent\Dental\Calendar::class,
            Controllers\CalendarsController::class,
            Resources\Calendar::class,
            Repositories\Calendars::class,
            Requests\Calendar::class,
        ],
        [
            Eloquent\Dental\Chair::class,
            Controllers\ChairsController::class,
            Resources\Chair::class,
            Repositories\Chairs::class,
            Requests\Chair::class,
        ],
        [
            Eloquent\Dental\ChangeList::class,
            Controllers\ChangeListsController::class,
            Resources\ChangeList::class,
            Repositories\ChangeLists::class,
            Requests\ChangeList::class,
        ],
        [
            Eloquent\Dental\Charge::class,
            Controllers\ChargesController::class,
            Resources\Charge::class,
            Repositories\Charges::class,
            Requests\Charge::class,
        ],
        [
            Eloquent\Dental\ClaimNoteAttachment::class,
            Controllers\ClaimNoteAttachmentsController::class,
            Resources\ClaimNoteAttachment::class,
            Repositories\ClaimNoteAttachments::class,
            Requests\ClaimNoteAttachment::class,
        ],
        [
            Eloquent\Company::class,
            Controllers\CompaniesController::class,
            Resources\Company::class,
            Repositories\Companies::class,
            Requests\Company::class,
        ],
        [
            Eloquent\Dental\Complaint::class,
            Controllers\ComplaintsController::class,
            Resources\Complaint::class,
            Repositories\Complaints::class,
            Requests\Complaint::class,
        ],
        [
            Eloquent\Dental\Contact::class,
            Controllers\ContactsController::class,
            Resources\Contact::class,
            Repositories\Contacts::class,
            Requests\Contact::class,
        ],
        [
            Eloquent\Dental\ContactType::class,
            Controllers\ContactTypesController::class,
            Resources\ContactType::class,
            Repositories\ContactTypes::class,
            Requests\ContactType::class,
        ],
        [
            Eloquent\Dental\CorporateContact::class,
            Controllers\CorporateContactsController::class,
            Resources\CorporateContact::class,
            Repositories\CorporateContacts::class,
            Requests\CorporateContact::class,
        ],
        [
            Eloquent\Dental\CustomLetterTemplate::class,
            Controllers\CustomLetterTemplatesController::class,
            Resources\CustomLetterTemplate::class,
            Repositories\CustomLetterTemplates::class,
            Requests\CustomLetterTemplate::class,
        ],
        [
            Eloquent\Dental\CustomText::class,
            Controllers\CustomTextsController::class,
            Resources\CustomText::class,
            Repositories\CustomTexts::class,
            Requests\CustomText::class,
],
        [
            Eloquent\Dental\DentalClinicalExam::class,
            Controllers\DentalClinicalExamsController::class,
            Resources\DentalClinicalExam::class,
            Repositories\DentalClinicalExams::class,
            Requests\DentalClinicalExam::class,
        ],
        [
            Eloquent\Dental\Device::class,
            Controllers\DevicesController::class,
            Resources\Device::class,
            Repositories\Devices::class,
            Requests\Device::class,
        ],
        [
            Eloquent\Dental\Diagnostic::class,
            Controllers\DiagnosticsController::class,
            Resources\Diagnostic::class,
            Repositories\Diagnostics::class,
            Requests\Diagnostic::class,
        ],
        [
            Eloquent\Dental\Document::class,
            Controllers\DocumentsController::class,
            Resources\Document::class,
            Repositories\Documents::class,
            Requests\Document::class,
        ],
        [
            Eloquent\Dental\DocumentCategory::class,
            Controllers\DocumentCategoriesController::class,
            Resources\DocumentCategory::class,
            Repositories\DocumentCategories::class,
            Requests\DocumentCategory::class,
        ],
        [
            Eloquent\Dental\EpworthSleepinessScale::class,
            Controllers\EpworthSleepinessScaleController::class,
            Resources\EpworthSleepinessScale::class,
            Repositories\EpworthSleepinessScale::class,
            Requests\EpworthSleepinessScale::class,
        ],
        [
            Eloquent\Dental\Fax::class,
            Controllers\FaxesController::class,
            Resources\Fax::class,
            Repositories\Faxes::class,
            Requests\Fax::class,
        ],
        [
            Eloquent\Dental\FaxInvoice::class,
            Controllers\FaxInvoicesController::class,
            Resources\FaxInvoice::class,
            Repositories\FaxInvoices::class,
            Requests\FaxInvoice::class,
        ],
        [
            Eloquent\Dental\GagReflex::class,
            Controllers\GagReflexesController::class,
            Resources\GagReflex::class,
            Repositories\GagReflexes::class,
            Requests\GagReflex::class,
        ],
        [
            Eloquent\Dental\GuideDevice::class,
            Controllers\GuideDevicesController::class,
            Resources\GuideDevice::class,
            Repositories\GuideDevices::class,
            Requests\GuideDevice::class,
        ],
        [
            Eloquent\Dental\GuideSetting::class,
            Controllers\GuideSettingsController::class,
            Resources\GuideSetting::class,
            Repositories\GuideSettings::class,
            Requests\GuideSetting::class,
        ],
        [
            Eloquent\Dental\GuideSettingOption::class,
            Controllers\GuideSettingOptionsController::class,
            Resources\GuideSettingOption::class,
            Repositories\GuideSettingOptions::class,
            Requests\GuideSettingOption::class,
        ],
        [
            Eloquent\Dental\HealthHistory::class,
            Controllers\HealthHistoriesController::class,
            Resources\HealthHistory::class,
            Repositories\HealthHistories::class,
            Requests\HealthHistory::class,
        ],
        [
            Eloquent\Dental\HomeSleepTest::class,
            Controllers\HomeSleepTestsController::class,
            Resources\HomeSleepTest::class,
            Repositories\HomeSleepTests::class,
            Requests\HomeSleepTest::class,
        ],
        [
            Eloquent\Dental\ImageType::class,
            Controllers\ImageTypesController::class,
            Resources\ImageType::class,
            Repositories\ImageTypes::class,
            Requests\ImageType::class,
        ],
        [
            Eloquent\Dental\InsDiagnosis::class,
            Controllers\InsuranceDiagnosesController::class,
            Resources\InsDiagnosis::class,
            Repositories\InsDiagnoses::class,
            Requests\InsuranceDiagnosis::class,
        ],
        [
            Eloquent\Dental\InsuranceDocument::class,
            Controllers\InsuranceDocumentsController::class,
            Resources\InsuranceDocument::class,
            Repositories\InsuranceDocuments::class,
            Requests\InsuranceDocument::class,
        ],
        [
            Eloquent\Dental\InsuranceFile::class,
            Controllers\InsuranceFilesController::class,
            Resources\InsuranceFile::class,
            Repositories\InsuranceFiles::class,
            Requests\InsuranceFile::class,
        ],
        [
            Eloquent\Dental\InsuranceHistory::class,
            Controllers\InsuranceHistoriesController::class,
            Resources\InsuranceHistory::class,
            Repositories\InsuranceHistories::class,
            Requests\InsuranceHistory::class,
        ],
        [
            Eloquent\Dental\InsurancePreauth::class,
            Controllers\InsurancePreauthController::class,
            Resources\InsurancePreauth::class,
            Repositories\InsurancePreauth::class,
            Requests\InsurancePreauth::class,
        ],
        [
            Eloquent\Dental\InsuranceType::class,
            Controllers\InsuranceTypesController::class,
            Resources\InsuranceType::class,
            Repositories\InsuranceTypes::class,
            Requests\InsuranceType::class,
        ],
        [
            Eloquent\Dental\Insurance::class,
            Controllers\InsurancesController::class,
            Resources\Insurance::class,
            Repositories\Insurances::class,
            Requests\Insurance::class,
        ],
        [
            Eloquent\Dental\Intolerance::class,
            Controllers\IntolerancesController::class,
            Resources\Intolerance::class,
            Repositories\Intolerances::class,
            Requests\Intolerance::class,
        ],
        [
            Eloquent\Dental\Joint::class,
            Controllers\JointsController::class,
            Resources\Joint::class,
            Repositories\Joints::class,
            Requests\Joint::class,
        ],
        [
            Eloquent\Dental\JointExam::class,
            Controllers\JointExamsController::class,
            Resources\JointExam::class,
            Repositories\JointExams::class,
            Requests\JointExam::class,
        ],
        [
            Eloquent\Dental\LedgerHistory::class,
            Controllers\LedgerHistoriesController::class,
            Resources\LedgerHistory::class,
            Repositories\LedgerHistories::class,
            Requests\LedgerHistory::class,
        ],
        [
            Eloquent\Dental\LedgerNote::class,
            Controllers\LedgerNotesController::class,
            Resources\LedgerNote::class,
            Repositories\LedgerNotes::class,
            Requests\LedgerNote::class,
        ],
        [
            Eloquent\Dental\LedgerPayment::class,
            Controllers\LedgerPaymentsController::class,
            Resources\LedgerPayment::class,
            Repositories\LedgerPayments::class,
            Requests\LedgerPayment::class,
        ],
        [
            Eloquent\Dental\LedgerRecord::class,
            Controllers\LedgerRecordsController::class,
            Resources\LedgerRecord::class,
            Repositories\LedgerRecords::class,
            Requests\LedgerRecord::class,
        ],
        [
            Eloquent\Dental\LedgerStatement::class,
            Controllers\LedgerStatementsController::class,
            Resources\LedgerStatement::class,
            Repositories\LedgerStatements::class,
            Requests\LedgerStatement::class,
        ],
        [
            Eloquent\Dental\Ledger::class,
            Controllers\LedgersController::class,
            Resources\Ledger::class,
            Repositories\Ledgers::class,
            Requests\Ledger::class,
        ],
        [
            Eloquent\Dental\LetterTemplate::class,
            Controllers\LetterTemplatesController::class,
            Resources\LetterTemplate::class,
            Repositories\LetterTemplates::class,
            Requests\LetterTemplate::class,
        ],
        [
            Eloquent\Dental\Letter::class,
            Controllers\LettersController::class,
            Resources\Letter::class,
            Repositories\Letters::class,
            Requests\Letter::class,
        ],
        [
            Eloquent\Dental\Location::class,
            Controllers\LocationsController::class,
            Resources\Location::class,
            Repositories\Locations::class,
            Requests\Location::class,
        ],
        [
            Eloquent\Dental\LoginDetail::class,
            Controllers\LoginDetailsController::class,
            Resources\LoginDetail::class,
            Repositories\LoginDetails::class,
            Requests\LoginDetail::class,
        ],
        [
            Eloquent\Dental\Login::class,
            Controllers\LoginsController::class,
            Resources\Login::class,
            Repositories\Logins::class,
            Requests\Login::class,
        ],
        [
            Eloquent\Dental\Mandible::class,
            Controllers\MandiblesController::class,
            Resources\Mandible::class,
            Repositories\Mandibles::class,
            Requests\Mandible::class,
        ],
        [
            Eloquent\Dental\Maxilla::class,
            Controllers\MaxillasController::class,
            Resources\Maxilla::class,
            Repositories\Maxillas::class,
            Requests\Maxilla::class,
        ],
        [
            Eloquent\Dental\MedicalHistory::class,
            Controllers\MedicalHistoriesController::class,
            Resources\MedicalHistory::class,
            Repositories\MedicalHistories::class,
            Requests\MedicalHistory::class,
        ],
        [
            Eloquent\Dental\Medicament::class,
            Controllers\MedicationsController::class,
            Resources\Medicament::class,
            Repositories\Medications::class,
            Requests\Medicament::class,
        ],
        [
            Eloquent\Dental\Note::class,
            Controllers\NotesController::class,
            Resources\Note::class,
            Repositories\Notes::class,
            Requests\Note::class,
        ],
        [
            Eloquent\Dental\Notification::class,
            Controllers\NotificationsController::class,
            Resources\Notification::class,
            Repositories\Notifications::class,
            Requests\Notification::class,
        ],
        [
            Eloquent\Dental\Palpation::class,
            Controllers\PalpationController::class,
            Resources\Palpation::class,
            Repositories\Palpation::class,
            Requests\Palpation::class,
        ],
        [
            Eloquent\Dental\PatientContact::class,
            Controllers\PatientContactsController::class,
            Resources\PatientContact::class,
            Repositories\PatientContacts::class,
            Requests\PatientContact::class,
        ],
        [
            Eloquent\Dental\PatientInsurance::class,
            Controllers\PatientInsurancesController::class,
            Resources\PatientInsurance::class,
            Repositories\PatientInsurances::class,
            Requests\PatientInsurance::class,
        ],
        [
            Eloquent\Dental\PatientSummary::class,
            Controllers\PatientSummariesController::class,
            Resources\PatientSummary::class,
            Repositories\PatientSummaries::class,
            Requests\PatientSummary::class,
        ],
        [
            Eloquent\Dental\Patient::class,
            Controllers\PatientsController::class,
            Resources\Patient::class,
            Repositories\Patients::class,
            Requests\Patient::class,
        ],
        [
            Eloquent\Payer::class,
            Controllers\PayersController::class,
            Resources\Payer::class,
            Repositories\Payers::class,
            Requests\Payer::class,
        ],
        [
            Eloquent\Dental\PaymentReport::class,
            Controllers\PaymentReportsController::class,
            Resources\PaymentReport::class,
            Repositories\PaymentReports::class,
            Requests\PaymentReport::class,
        ],
        [
            Eloquent\Dental\PlaceService::class,
            Controllers\PlaceServicesController::class,
            Resources\PlaceService::class,
            Repositories\PlaceServices::class,
            Requests\PlaceService::class,
        ],
        [
            Eloquent\Dental\Plan::class,
            Controllers\PlansController::class,
            Resources\Plan::class,
            Repositories\Plans::class,
            Requests\Plan::class,
        ],
        [
            Eloquent\Dental\PreviousTreatment::class,
            Controllers\PreviousTreatmentsController::class,
            Resources\PreviousTreatment::class,
            Repositories\PreviousTreatments::class,
            Requests\PreviousTreatment::class,
        ],
        [
            Eloquent\Dental\ProfileImage::class,
            Controllers\ProfileImagesController::class,
            Resources\ProfileImage::class,
            Repositories\ProfileImages::class,
            Requests\ProfileImage::class,
        ],
        [
            Eloquent\Dental\Qualifier::class,
            Controllers\QualifiersController::class,
            Resources\Qualifier::class,
            Repositories\Qualifiers::class,
            Requests\Qualifier::class,
        ],
        [
            Eloquent\Dental\Recipient::class,
            Controllers\RecipientsController::class,
            Resources\Recipient::class,
            Repositories\Recipients::class,
            Requests\Recipient::class,
        ],
        [
            Eloquent\Dental\ReferredByContact::class,
            Controllers\ReferredByContactsController::class,
            Resources\ReferredByContact::class,
            Repositories\ReferredByContacts::class,
            Requests\ReferredByContact::class,
        ],
        [
            Eloquent\Dental\Refund::class,
            Controllers\RefundsController::class,
            Resources\Refund::class,
            Repositories\Refunds::class,
            Requests\Refund::class,
        ],
        [
            Eloquent\Dental\ScreenerEpworth::class,
            Controllers\ScreenerEpworthController::class,
            Resources\ScreenerEpworth::class,
            Repositories\ScreenerEpworth::class,
            Requests\ScreenerEpworth::class,
        ],
        [
            Eloquent\Dental\Screener::class,
            Controllers\ScreenersController::class,
            Resources\Screener::class,
            Repositories\Screeners::class,
            Requests\Screener::class,
        ],
        [
            Eloquent\Dental\Sleeplab::class,
            Controllers\SleeplabsController::class,
            Resources\Sleeplab::class,
            Repositories\Sleeplabs::class,
            Requests\Sleeplab::class,
        ],
        [
            Eloquent\Dental\SleepStudy::class,
            Controllers\SleepStudiesController::class,
            Resources\SleepStudy::class,
            Repositories\SleepStudies::class,
            Requests\SleepStudy::class,
        ],
        [
            Eloquent\Dental\SleepTest::class,
            Controllers\SleepTestsController::class,
            Resources\SleepTest::class,
            Repositories\SleepTests::class,
            Requests\SleepTest::class,
        ],
        [
            Eloquent\Dental\SocialHistory::class,
            Controllers\SocialHistoriesController::class,
            Resources\SocialHistory::class,
            Repositories\SocialHistories::class,
            Requests\SocialHistory::class,
        ],
        [
            Eloquent\Dental\SoftPalate::class,
            Controllers\SoftPalatesController::class,
            Resources\SoftPalate::class,
            Repositories\SoftPalates::class,
            Requests\SoftPalate::class,
        ],
        [
            Eloquent\Dental\Summary::class,
            Controllers\SummariesController::class,
            Resources\Summary::class,
            Repositories\Summaries::class,
            Requests\Summary::class,
        ],
        [
            Eloquent\Dental\SupportTicket::class,
            Controllers\SupportTicketsController::class,
            Resources\SupportTicket::class,
            Repositories\SupportTickets::class,
            Requests\SupportTicket::class,
        ],
        [
            Eloquent\Dental\Symptom::class,
            Controllers\SymptomsController::class,
            Resources\Symptom::class,
            Repositories\Symptoms::class,
            Requests\Symptom::class,
        ],
        [
            Eloquent\Dental\Task::class,
            Controllers\TasksController::class,
            Resources\Task::class,
            Repositories\Tasks::class,
            Requests\Task::class,
        ],
        [
            Eloquent\Dental\TmjClinicalExam::class,
            Controllers\TmjClinicalExamsController::class,
            Resources\TmjClinicalExam::class,
            Repositories\TmjClinicalExams::class,
            Requests\TmjClinicalExam::class,
        ],
        [
            Eloquent\Dental\TongueClinicalExam::class,
            Controllers\TongueClinicalExamsController::class,
            Resources\TongueClinicalExam::class,
            Repositories\TongueClinicalExams::class,
            Requests\TongueClinicalExam::class,
        ],
        [
            Eloquent\Dental\TonsilsClinicalExam::class,
            Controllers\TonsilsClinicalExamsController::class,
            Resources\TonsilsClinicalExam::class,
            Repositories\TonsilsClinicalExams::class,
            Requests\TonsilsClinicalExam::class,
        ],
        [
            Eloquent\Dental\User::class,
            Controllers\UsersController::class,
            Resources\User::class,
            Repositories\Users::class,
            Requests\User::class,
        ],
    ];

    const EXTERNAL_BINDINGS = [
        [
            Eloquent\Dental\ExternalCompany::class,
            Resources\ExternalCompany::class,
            Repositories\ExternalCompanies::class,
        ],
        [
            Eloquent\Dental\ExternalUser::class,
            Resources\ExternalUser::class,
            Repositories\ExternalUsers::class,
        ],
        [
            Eloquent\Dental\ExternalPatient::class,
            Resources\ExternalPatient::class,
            Repositories\ExternalPatients::class,
        ],
        [
            Eloquent\Dental\ExternalCompanyUser::class,
            Resources\ExternalCompanyUser::class,
            Repositories\ExternalCompanyUsers::class,
        ],
    ];

    /**
     * @return Bindings[]
     */
    public static function setBindings()
    {
        $bindingObjects = [];
        foreach (self::BINDINGS as $binding) {
            $bindingObject = new Bindings();
            $bindingObject
                ->setModel($binding[self::MODEL_KEY])
                ->setController($binding[self::CONTROLLER_KEY])
                ->setResource($binding[self::RESOURCE_KEY])
                ->setRepository($binding[self::REPOSITORY_KEY])
                ->setRequest($binding[self::REQUEST_KEY])
            ;
            $bindingObjects[] = $bindingObject;
        }
        return $bindingObjects;
    }

    /**
     * @return Bindings[]
     */
    public static function setExternalBindings()
    {
        $bindingObjects = [];
        foreach (self::EXTERNAL_BINDINGS as $binding) {
            $bindingObject = new Bindings();
            $bindingObject
                ->setModel($binding[self::EXTERNAL_MODEL_KEY])
                ->setResource($binding[self::EXTERNAL_RESOURCE_KEY])
                ->setRepository($binding[self::EXTERNAL_REPOSITORY_KEY])
            ;
            $bindingObjects[] = $bindingObject;
        }
        return $bindingObjects;
    }
}
