<?php

namespace DentalSleepSolutions\StaticClasses;

use DentalSleepSolutions\Eloquent;
use DentalSleepSolutions\Contracts\Repositories;
use DentalSleepSolutions\Contracts\Resources;
use DentalSleepSolutions\Structs\Bindings;
use DentalSleepSolutions\Http\Controllers;
use DentalSleepSolutions\Http\Requests;

class BindingSetter
{
    const ROUTE_KEY = 0;
    const MODEL_KEY = 1;
    const CONTROLLER_KEY = 2;
    const RESOURCE_KEY = 3;
    const REPOSITORY_KEY = 4;
    const STORE_REQUEST_KEY = 5;
    const UPDATE_REQUEST_KEY = 6;
    const DESTROY_REQUEST_KEY = 7;

    // TODO: this mega-constant should be replaced by a naming convention and reflection API
    const BINDINGS = [
        [
            'access-codes',
            Eloquent\Dental\AccessCode::class,
            Controllers\AccessCodesController::class,
            Resources\AccessCode::class,
            Repositories\AccessCodes::class,
            Requests\AccessCodeStore::class,
            Requests\AccessCodeUpdate::class,
            Requests\AccessCodeDestroy::class,
        ],
        [
            'admins',
            Eloquent\Admin::class,
            Controllers\AdminsController::class,
            Resources\Admin::class,
            Repositories\Admins::class,
            Requests\AdminStore::class,
            Requests\AdminUpdate::class,
            Requests\AdminDestroy::class,
        ],
        [
            'airway-evaluations',
            Eloquent\Dental\AirwayEvaluation::class,
            Controllers\AirwayEvaluationsController::class,
            Resources\AirwayEvaluation::class,
            Repositories\AirwayEvaluations::class,
            Requests\AirwayEvaluationStore::class,
            Requests\AirwayEvaluationUpdate::class,
            Requests\AirwayEvaluationDestroy::class,
        ],
        [
            'allergens',
            Eloquent\Dental\Allergen::class,
            Controllers\AllergensController::class,
            Resources\Allergen::class,
            Repositories\Allergens::class,
            Requests\AllergenStore::class,
            Requests\AllergenUpdate::class,
            Requests\AllergenDestroy::class,
        ],
        [
            'appt-types',
            Eloquent\Dental\AppointmentType::class,
            Controllers\AppointmentTypesController::class,
            Resources\AppointmentType::class,
            Repositories\AppointmentTypes::class,
            Requests\AppointmentTypeStore::class,
            Requests\AppointmentTypeUpdate::class,
            Requests\AppointmentTypeDestroy::class,
        ],
        [
            'calendars',
            Eloquent\Dental\Calendar::class,
            Controllers\CalendarsController::class,
            Resources\Calendar::class,
            Repositories\Calendars::class,
            Requests\CalendarStore::class,
            Requests\CalendarUpdate::class,
            Requests\CalendarDestroy::class,
        ],
        [
            'chairs',
            Eloquent\Dental\Chair::class,
            Controllers\ChairsController::class,
            Resources\Chair::class,
            Repositories\Chairs::class,
            Requests\ChairStore::class,
            Requests\ChairUpdate::class,
            Requests\ChairDestroy::class,
        ],
        [
            'change-lists',
            Eloquent\Dental\ChangeList::class,
            Controllers\ChangeListsController::class,
            Resources\ChangeList::class,
            Repositories\ChangeLists::class,
            Requests\ChangeListStore::class,
            Requests\ChangeListUpdate::class,
            Requests\ChangeListDestroy::class,
        ],
        [
            'charges',
            Eloquent\Dental\Charge::class,
            Controllers\ChargesController::class,
            Resources\Charge::class,
            Repositories\Charges::class,
            Requests\ChargeStore::class,
            Requests\ChargeUpdate::class,
            Requests\ChargeDestroy::class,
        ],
        [
            'claim-note-attachments',
            Eloquent\Dental\ClaimNoteAttachment::class,
            Controllers\ClaimNoteAttachmentsController::class,
            Resources\ClaimNoteAttachment::class,
            Repositories\ClaimNoteAttachments::class,
            Requests\ClaimNoteAttachmentStore::class,
            Requests\ClaimNoteAttachmentUpdate::class,
            Requests\ClaimNoteAttachmentDestroy::class,
        ],
        [
            'companies',
            Eloquent\Company::class,
            Controllers\CompaniesController::class,
            Resources\Company::class,
            Repositories\Companies::class,
            Requests\CompanyStore::class,
            Requests\CompanyUpdate::class,
            Requests\CompanyDestroy::class,
        ],
        [
            'complaints',
            Eloquent\Dental\Complaint::class,
            Controllers\ComplaintsController::class,
            Resources\Complaint::class,
            Repositories\Complaints::class,
            Requests\ComplaintStore::class,
            Requests\ComplaintUpdate::class,
            Requests\ComplaintDestroy::class,
        ],
        [
            'contacts',
            Eloquent\Dental\Contact::class,
            Controllers\ContactsController::class,
            Resources\Contact::class,
            Repositories\Contacts::class,
            Requests\ContactStore::class,
            Requests\ContactUpdate::class,
            Requests\ContactDestroy::class,
        ],
        [
            'contact-types',
            Eloquent\Dental\ContactType::class,
            Controllers\ContactTypesController::class,
            Resources\ContactType::class,
            Repositories\ContactTypes::class,
            Requests\ContactTypeStore::class,
            Requests\ContactTypeUpdate::class,
            Requests\ContactTypeDestroy::class,
        ],
        [
            'corporate-contacts',
            Eloquent\Dental\CorporateContact::class,
            Controllers\CorporateContactsController::class,
            Resources\CorporateContact::class,
            Repositories\CorporateContacts::class,
            Requests\CorporateContactStore::class,
            Requests\CorporateContactUpdate::class,
            Requests\CorporateContactDestroy::class,
        ],
        [
            'custom-letter-templates',
            Eloquent\Dental\CustomLetterTemplate::class,
            Controllers\CustomLetterTemplatesController::class,
            Resources\CustomLetterTemplate::class,
            Repositories\CustomLetterTemplates::class,
            Requests\CustomLetterTemplateStore::class,
            Requests\CustomLetterTemplateUpdate::class,
            Requests\CustomLetterTemplateDestroy::class,
        ],
        [
            'custom-texts',
            Eloquent\Dental\CustomText::class,
            Controllers\CustomTextsController::class,
            Resources\CustomText::class,
            Repositories\CustomTexts::class,
            Requests\CustomTextStore::class,
            Requests\CustomTextUpdate::class,
            Requests\CustomTextDestroy::class,
        ],
        [
            'dental-clinical-exams',
            Eloquent\Dental\DentalClinicalExam::class,
            Controllers\DentalClinicalExamsController::class,
            Resources\DentalClinicalExam::class,
            Repositories\DentalClinicalExams::class,
            Requests\DentalClinicalExamStore::class,
            Requests\DentalClinicalExamUpdate::class,
            Requests\DentalClinicalExamDestroy::class,
        ],
        [
            'devices',
            Eloquent\Dental\Device::class,
            Controllers\DevicesController::class,
            Resources\Device::class,
            Repositories\Devices::class,
            Requests\DeviceStore::class,
            Requests\DeviceUpdate::class,
            Requests\DeviceDestroy::class,
        ],
        [
            'diagnostics',
            Eloquent\Dental\Diagnostic::class,
            Controllers\DiagnosticsController::class,
            Resources\Diagnostic::class,
            Repositories\Diagnostics::class,
            Requests\DiagnosticStore::class,
            Requests\DiagnosticUpdate::class,
            Requests\DiagnosticDestroy::class,
        ],
        [
            'documents',
            Eloquent\Dental\Document::class,
            Controllers\DocumentsController::class,
            Resources\Document::class,
            Repositories\Documents::class,
            Requests\DocumentStore::class,
            Requests\DocumentUpdate::class,
            Requests\DocumentDestroy::class,
        ],
        [
            'document-categories',
            Eloquent\Dental\DocumentCategory::class,
            Controllers\DocumentCategoriesController::class,
            Resources\DocumentCategory::class,
            Repositories\DocumentCategories::class,
            Requests\DocumentCategoryStore::class,
            Requests\DocumentCategoryUpdate::class,
            Requests\DocumentCategoryDestroy::class,
        ],
        [
            'epworth-sleepiness-scale',
            Eloquent\Dental\EpworthSleepinessScale::class,
            Controllers\EpworthSleepinessScaleController::class,
            Resources\EpworthSleepinessScale::class,
            Repositories\EpworthSleepinessScale::class,
            Requests\EpworthSleepinessScaleStore::class,
            Requests\EpworthSleepinessScaleUpdate::class,
            Requests\EpworthSleepinessScaleDestroy::class,
        ],
        [
            'faxes',
            Eloquent\Dental\Fax::class,
            Controllers\FaxesController::class,
            Resources\Fax::class,
            Repositories\Faxes::class,
            Requests\FaxStore::class,
            Requests\FaxUpdate::class,
            Requests\FaxDestroy::class,
        ],
        [
            'fax-invoices',
            Eloquent\Dental\FaxInvoice::class,
            Controllers\FaxInvoicesController::class,
            Resources\FaxInvoice::class,
            Repositories\FaxInvoices::class,
            Requests\FaxInvoiceStore::class,
            Requests\FaxInvoiceUpdate::class,
            Requests\FaxInvoiceDestroy::class,
        ],
        [
            'gag-reflexes',
            Eloquent\Dental\GagReflex::class,
            Controllers\GagReflexesController::class,
            Resources\GagReflex::class,
            Repositories\GagReflexes::class,
            Requests\GagReflexStore::class,
            Requests\GagReflexUpdate::class,
            Requests\GagReflexDestroy::class,
        ],
        [
            'guide-devices',
            Eloquent\Dental\GuideDevice::class,
            Controllers\GuideDevicesController::class,
            Resources\GuideDevice::class,
            Repositories\GuideDevices::class,
            Requests\GuideDeviceStore::class,
            Requests\GuideDeviceUpdate::class,
            Requests\GuideDeviceDestroy::class,
        ],
        [
            'guide-settings',
            Eloquent\Dental\GuideSetting::class,
            Controllers\GuideSettingsController::class,
            Resources\GuideSetting::class,
            Repositories\GuideSettings::class,
            Requests\GuideSettingStore::class,
            Requests\GuideSettingUpdate::class,
            Requests\GuideSettingDestroy::class,
        ],
        [
            'guide-setting-options',
            Eloquent\Dental\GuideSettingOption::class,
            Controllers\GuideSettingOptionsController::class,
            Resources\GuideSettingOption::class,
            Repositories\GuideSettingOptions::class,
            Requests\GuideSettingOptionStore::class,
            Requests\GuideSettingOptionUpdate::class,
            Requests\GuideSettingOptionDestroy::class,
        ],
        [
            'health-histories',
            Eloquent\Dental\HealthHistory::class,
            Controllers\HealthHistoriesController::class,
            Resources\HealthHistory::class,
            Repositories\HealthHistories::class,
            Requests\HealthHistoryStore::class,
            Requests\HealthHistoryUpdate::class,
            Requests\HealthHistoryDestroy::class,
        ],
        [
            'home-sleep-tests',
            Eloquent\Dental\HomeSleepTest::class,
            Controllers\HomeSleepTestsController::class,
            Resources\HomeSleepTest::class,
            Repositories\HomeSleepTests::class,
            Requests\HomeSleepTestStore::class,
            Requests\HomeSleepTestUpdate::class,
            Requests\HomeSleepTestDestroy::class,
        ],
        [
            'image-types',
            Eloquent\Dental\ImageType::class,
            Controllers\ImageTypesController::class,
            Resources\ImageType::class,
            Repositories\ImageTypes::class,
            Requests\ImageTypeStore::class,
            Requests\ImageTypeUpdate::class,
            Requests\ImageTypeDestroy::class,
        ],
        [
            'insurance-diagnoses',
            Eloquent\Dental\InsDiagnosis::class,
            Controllers\InsuranceDiagnosesController::class,
            Resources\InsDiagnosis::class,
            Repositories\InsDiagnoses::class,
            Requests\InsuranceDiagnosisStore::class,
            Requests\InsuranceDiagnosisUpdate::class,
            Requests\InsuranceDiagnosisDestroy::class,
        ],
        [
            'insurance-documents',
            Eloquent\Dental\InsuranceDocument::class,
            Controllers\InsuranceDocumentsController::class,
            Resources\InsuranceDocument::class,
            Repositories\InsuranceDocuments::class,
            Requests\InsuranceDocumentStore::class,
            Requests\InsuranceDocumentUpdate::class,
            Requests\InsuranceDocumentDestroy::class,
        ],
        [
            'insurance-files',
            Eloquent\Dental\InsuranceFile::class,
            Controllers\InsuranceFilesController::class,
            Resources\InsuranceFile::class,
            Repositories\InsuranceFiles::class,
            Requests\InsuranceFileStore::class,
            Requests\InsuranceFileUpdate::class,
            Requests\InsuranceFileDestroy::class,
        ],
        [
            'insurance-histories',
            Eloquent\Dental\InsuranceHistory::class,
            Controllers\InsuranceHistoriesController::class,
            Resources\InsuranceHistory::class,
            Repositories\InsuranceHistories::class,
            Requests\InsuranceHistoryStore::class,
            Requests\InsuranceHistoryUpdate::class,
            Requests\InsuranceHistoryDestroy::class,
        ],
        Eloquent\Dental\InsurancePreauth::class => [Repositories\InsurancePreauth::class, Resources\InsurancePreauth::class],
        Eloquent\Dental\InsuranceType::class => [Repositories\InsuranceTypes::class, Resources\InsuranceType::class],
        Eloquent\Dental\Insurance::class => [Repositories\Insurances::class, Resources\Insurance::class],
        Eloquent\Dental\Intolerance::class => [Repositories\Intolerances::class, Resources\Intolerance::class],
        Eloquent\Dental\Joint::class => [Repositories\Joints::class, Resources\Joint::class],
        Eloquent\Dental\JointExam::class => [Repositories\JointExams::class, Resources\JointExam::class],
        Eloquent\Dental\Ledger::class => [Repositories\Ledgers::class, Resources\Ledger::class],
        Eloquent\Dental\LedgerHistory::class => [Repositories\LedgerHistories::class, Resources\LedgerHistory::class],
        Eloquent\Dental\LedgerNote::class => [Repositories\LedgerNotes::class, Resources\LedgerNote::class],
        Eloquent\Dental\LedgerPayment::class => [Repositories\LedgerPayments::class, Resources\LedgerPayment::class],
        Eloquent\Dental\LedgerRecord::class => [Repositories\LedgerRecords::class, Resources\LedgerRecord::class],
        Eloquent\Dental\LedgerStatement::class => [Repositories\LedgerStatements::class, Resources\LedgerStatement::class],
        Eloquent\Dental\Letter::class => [Repositories\Letters::class, Resources\Letter::class],
        Eloquent\Dental\LetterTemplate::class => [Repositories\LetterTemplates::class, Resources\LetterTemplate::class],
        Eloquent\Dental\Location::class => [Repositories\Locations::class, Resources\Location::class],
        Eloquent\Dental\Login::class => [Repositories\Logins::class, Resources\Login::class],
        Eloquent\Dental\LoginDetail::class => [Repositories\LoginDetails::class, Resources\LoginDetail::class],
        Eloquent\Dental\Mandible::class => [Repositories\Mandibles::class, Resources\Mandible::class],
        Eloquent\Dental\Maxilla::class => [Repositories\Maxillas::class, Resources\Maxilla::class],
        Eloquent\Dental\MedicalHistory::class => [Repositories\MedicalHistories::class, Resources\MedicalHistory::class],
        Eloquent\Dental\Medicament::class => [Repositories\Medications::class, Resources\Medicament::class],
        Eloquent\Dental\Note::class => [Repositories\Notes::class, Resources\Note::class],
        Eloquent\Dental\Notification::class => [Repositories\Notifications::class, Resources\Notification::class],
        Eloquent\Dental\Palpation::class => [Repositories\Palpation::class, Resources\Palpation::class],
        Eloquent\Dental\Patient::class => [Repositories\Patients::class, Resources\Patient::class],
        Eloquent\Dental\PatientContact::class => [Repositories\PatientContacts::class, Resources\PatientContact::class],
        Eloquent\Dental\PatientInsurance::class => [Repositories\PatientInsurances::class, Resources\PatientInsurance::class],
        Eloquent\Dental\PatientSummary::class => [Repositories\PatientSummaries::class, Resources\PatientSummary::class],
        Eloquent\Dental\PaymentReport::class => [Repositories\PaymentReports::class, Resources\PaymentReport::class],
        Eloquent\Dental\PlaceService::class => [Repositories\PlaceServices::class, Resources\PlaceService::class],
        Eloquent\Dental\Plan::class => [Repositories\Plans::class, Resources\Plan::class],
        Eloquent\Dental\PreviousTreatment::class => [Repositories\PreviousTreatments::class, Resources\PreviousTreatment::class],
        Eloquent\Dental\ProfileImage::class => [Repositories\ProfileImages::class, Resources\ProfileImage::class],
        Eloquent\Dental\Qualifier::class => [Repositories\Qualifiers::class, Resources\Qualifier::class],
        Eloquent\Dental\Recipient::class => [Repositories\Recipients::class, Resources\Recipient::class],
        Eloquent\Dental\ReferredByContact::class => [Repositories\ReferredByContacts::class, Resources\ReferredByContact::class],
        Eloquent\Dental\Refund::class => [Repositories\Refunds::class, Resources\Refund::class],
        Eloquent\Dental\Screener::class => [Repositories\Screeners::class, Resources\Screener::class],
        Eloquent\Dental\ScreenerEpworth::class => [Repositories\ScreenerEpworth::class, Resources\ScreenerEpworth::class],
        Eloquent\Dental\Sleeplab::class => [Repositories\Sleeplabs::class, Resources\Sleeplab::class],
        Eloquent\Dental\SleepStudy::class => [Repositories\SleepStudies::class, Resources\SleepStudy::class],
        Eloquent\Dental\SleepTest::class => [Repositories\SleepTests::class, Resources\SleepTest::class],
        Eloquent\Dental\SocialHistory::class => [Repositories\SocialHistories::class, Resources\SocialHistory::class],
        Eloquent\Dental\SoftPalate::class => [Repositories\SoftPalates::class, Resources\SoftPalate::class],
        Eloquent\Dental\Summary::class => [Repositories\Summaries::class, Resources\Summary::class],
        Eloquent\Dental\SupportTicket::class => [Repositories\SupportTickets::class, Resources\SupportTicket::class],
        Eloquent\Dental\Symptom::class => [Repositories\Symptoms::class, Resources\Symptom::class],
        Eloquent\Dental\Task::class => [Repositories\Tasks::class, Resources\Task::class],
        Eloquent\Dental\TmjClinicalExam::class => [Repositories\TmjClinicalExams::class, Resources\TmjClinicalExam::class],
        Eloquent\Dental\TongueClinicalExam::class => [Repositories\TongueClinicalExams::class, Resources\TongueClinicalExam::class],
        Eloquent\Dental\TonsilsClinicalExam::class => [Repositories\TonsilsClinicalExams::class, Resources\TonsilsClinicalExam::class],
        Eloquent\Dental\User::class => [Repositories\Users::class, Resources\User::class],
        Eloquent\Dental\ExternalCompany::class => [Repositories\ExternalCompanies::class, Resources\ExternalCompany::class],
        Eloquent\Dental\ExternalUser::class => [Repositories\ExternalUsers::class, Resources\ExternalUser::class],
        Eloquent\Dental\ExternalPatient::class => [Repositories\ExternalPatients::class, Resources\ExternalPatient::class],
        Eloquent\Dental\ExternalCompanyUser::class => [Repositories\ExternalCompanyUsers::class, Resources\ExternalCompanyUser::class],
        Eloquent\Payer::class => [Repositories\Payers::class, Resources\Device::class],
    ];

    /**
     * @return Bindings[]
     */
    public static function setBindings()
    {
        $bindingObjects = [];
        foreach (self::BINDINGS as $binding) {
            $bindingObject = new Bindings();
            $bindingObject
                ->setRoute($binding[self::ROUTE_KEY])
                ->setModel($binding[self::MODEL_KEY])
                ->setController($binding[self::CONTROLLER_KEY])
                ->setResource($binding[self::RESOURCE_KEY])
                ->setRepository($binding[self::REPOSITORY_KEY])
                ->setStoreRequest($binding[self::STORE_REQUEST_KEY])
                ->setUpdateRequest($binding[self::UPDATE_REQUEST_KEY])
                ->setDestroyRequest($binding[self::DESTROY_REQUEST_KEY])
            ;
            $bindingObjects[] = $bindingObject;
        }
        return $bindingObjects;
    }
}
