CREATE TABLE `dental_insurance_preauth` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `patient_id` int(11) NOT NULL,
  `doc_id` int(11) NOT NULL,
  `ins_co` varchar(255) DEFAULT NULL,
  `ins_rank` varchar(255) NOT NULL DEFAULT 'primary',
  `ins_phone` varchar(255) DEFAULT NULL,
  `patient_ins_group_id` varchar(255) DEFAULT NULL,
  `patient_ins_id` varchar(255) DEFAULT NULL,
  `patient_firstname` varchar(255) DEFAULT NULL,
  `patient_lastname` varchar(255) DEFAULT NULL,
  `patient_add1` varchar(255) DEFAULT NULL,
  `patient_add2` varchar(255) DEFAULT NULL,
  `patient_city` varchar(255) DEFAULT NULL,
  `patient_state` varchar(255) DEFAULT NULL,
  `patient_zip` varchar(255) DEFAULT NULL,
  `patient_dob` varchar(255) DEFAULT NULL,
  `insured_first_name` varchar(255) DEFAULT NULL,
  `insured_last_name` varchar(255) DEFAULT NULL,
  `insured_dob` varchar(255) DEFAULT NULL,
  `doc_npi` varchar(255) DEFAULT NULL,
  `referring_doc_npi` varchar(255) DEFAULT NULL,
  `trxn_code_amount` decimal(11,2) DEFAULT NULL,
  `diagnosis_code` varchar(255) DEFAULT NULL,
  `date_of_call` varchar(255) DEFAULT NULL,
  `insurance_rep` varchar(255) DEFAULT NULL,
  `call_reference_num` varchar(255) DEFAULT NULL,
  `doc_medicare_npi` varchar(255) DEFAULT NULL,
  `doc_tax_id_or_ssn` varchar(255) DEFAULT NULL,
  `ins_effective_date` varchar(255) DEFAULT NULL,
  `ins_cal_year_start` varchar(255) DEFAULT NULL,
  `ins_cal_year_end` varchar(255) DEFAULT NULL,
  `trxn_code_covered` int(1) NOT NULL DEFAULT '0',
  `code_covered_notes` text,
  `has_out_of_network_benefits` int(1) NOT NULL DEFAULT '0',
  `out_of_network_percentage` int(11) DEFAULT NULL,
  `is_hmo` int(1) NOT NULL DEFAULT '0',
  `hmo_date_called` varchar(255) DEFAULT NULL,
  `hmo_date_received` varchar(255) DEFAULT NULL,
  `hmo_needs_auth` int(1) NOT NULL DEFAULT '0',
  `hmo_auth_date_requested` varchar(255) DEFAULT NULL,
  `hmo_auth_date_received` varchar(255) DEFAULT NULL,
  `hmo_auth_notes` text,
  `in_network_percentage` int(11) DEFAULT NULL,
  `in_network_appeal_date_sent` varchar(255) DEFAULT NULL,
  `in_network_appeal_date_received` varchar(255) DEFAULT NULL,
  `is_pre_auth_required` int(1) NOT NULL DEFAULT '0',
  `verbal_pre_auth_name` varchar(255) DEFAULT NULL,
  `verbal_pre_auth_ref_num` varchar(255) DEFAULT NULL,
  `verbal_pre_auth_notes` text,
  `written_pre_auth_notes` text,
  `written_pre_auth_date_received` varchar(255) DEFAULT NULL,
  `front_office_request_date` datetime DEFAULT NULL,
  `status` int(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;