<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDentalInsuranceTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('dental_insurance', function(Blueprint $table)
		{
			$table->increments('insuranceid');

			$table->integer('formid')->default(0);
			$table->integer('patientid')->default(0);
			$table->string('pica1')->nullable();
			$table->string('pica2')->nullable();
			$table->string('pica3')->nullable();
			$table->text('insurance_type')->nullable();
			$table->string('insured_id_number')->nullable();
			$table->string('patient_firstname')->nullable();
			$table->string('patient_lastname')->nullable();
			$table->string('patient_middle')->nullable();
			$table->string('patient_dob')->nullable();
			$table->string('patient_sex')->nullable();
			$table->string('insured_firstname')->nullable();
			$table->string('insured_lastname')->nullable();
			$table->string('insured_middle')->nullable();
			$table->string('patient_address')->nullable();
			$table->string('patient_relation_insured')->nullable();
			$table->string('insured_address')->nullable();
			$table->string('patient_city')->nullable();
			$table->string('patient_state')->nullable();
			$table->text('patient_status')->nullable();
			$table->string('insured_city')->nullable();
			$table->string('insured_state')->nullable();
			$table->string('patient_zip')->nullable();
			$table->string('patient_phone_code')->nullable();
			$table->string('patient_phone')->nullable();
			$table->string('insured_zip')->nullable();
			$table->string('insured_phone_code')->nullable();
			$table->string('insured_phone')->nullable();
			$table->string('other_insured_firstname')->nullable();
			$table->string('other_insured_lastname')->nullable();
			$table->string('other_insured_middle')->nullable();
			$table->string('employment')->nullable();
			$table->string('auto_accident')->nullable();
			$table->string('auto_accident_place')->nullable();
			$table->string('other_accident')->nullable();
			$table->string('insured_policy_group_feca')->nullable();
			$table->string('other_insured_policy_group_feca')->nullable();
			$table->string('insured_dob')->nullable();
			$table->string('insured_sex')->nullable();
			$table->string('other_insured_dob')->nullable();
			$table->string('other_insured_sex')->nullable();
			$table->string('insured_employer_school_name')->nullable();
			$table->string('other_insured_employer_school_name')->nullable();
			$table->string('insured_insurance_plan')->nullable();
			$table->string('other_insured_insurance_plan')->nullable();
			$table->string('reserved_local_use')->nullable();
			$table->string('another_plan')->nullable();
			$table->string('patient_signature')->nullable();
			$table->string('patient_signed_date')->nullable();
			$table->string('insured_signature')->nullable();
			$table->text('date_current')->nullable();
			$table->text('date_same_illness')->nullable();
			$table->text('unable_date_from')->nullable();
			$table->text('unable_date_to')->nullable();
			$table->text('referring_provider')->nullable();
			$table->text('field_17a_dd')->nullable();
			$table->text('field_17a')->nullable();
			$table->text('field_17b')->nullable();
			$table->text('hospitalization_date_from')->nullable();
			$table->text('hospitalization_date_to')->nullable();
			$table->text('reserved_local_use1')->nullable();
			$table->text('outside_lab')->nullable();
			$table->text('s_charges')->nullable();
			$table->text('diagnosis_1')->nullable();
			$table->text('diagnosis_2')->nullable();
			$table->text('diagnosis_3')->nullable();
			$table->text('diagnosis_4')->nullable();
			$table->text('medicaid_resubmission_code')->nullable();
			$table->text('original_ref_no')->nullable();
			$table->text('prior_authorization_number')->nullable();
			$table->text('service_date1_from')->nullable();
			$table->text('service_date1_to')->nullable();
			$table->text('place_of_service1')->nullable();
			$table->text('emg1')->nullable();
			$table->text('cpt_hcpcs1')->nullable();
			$table->text('modifier1_1')->nullable();
			$table->text('modifier1_2')->nullable();
			$table->text('modifier1_3')->nullable();
			$table->text('modifier1_4')->nullable();
			$table->text('diagnosis_pointer1')->nullable();
			$table->text('s_charges1_1')->nullable();
			$table->text('s_charges1_2')->nullable();
			$table->text('days_or_units1')->nullable();
			$table->text('epsdt_family_plan1')->nullable();
			$table->text('id_qua1')->nullable();
			$table->text('rendering_provider_id1')->nullable();
			$table->text('service_date2_from')->nullable();
			$table->text('service_date2_to')->nullable();
			$table->text('place_of_service2')->nullable();
			$table->text('emg2')->nullable();
			$table->text('cpt_hcpcs2')->nullable();
			$table->text('modifier2_1')->nullable();
			$table->text('modifier2_2')->nullable();
			$table->text('modifier2_3')->nullable();
			$table->text('modifier2_4')->nullable();
			$table->text('diagnosis_pointer2')->nullable();
			$table->text('s_charges2_1')->nullable();
			$table->text('s_charges2_2')->nullable();
			$table->text('days_or_units2')->nullable();
			$table->text('epsdt_family_plan2')->nullable();
			$table->text('id_qua2')->nullable();
			$table->text('rendering_provider_id2')->nullable();
			$table->text('service_date3_from')->nullable();
			$table->text('service_date3_to')->nullable();
			$table->text('place_of_service3')->nullable();
			$table->text('emg3')->nullable();
			$table->text('cpt_hcpcs3')->nullable();
			$table->text('modifier3_1')->nullable();
			$table->text('modifier3_2')->nullable();
			$table->text('modifier3_3')->nullable();
			$table->text('modifier3_4')->nullable();
			$table->text('diagnosis_pointer3')->nullable();
			$table->text('s_charges3_1')->nullable();
			$table->text('s_charges3_2')->nullable();
			$table->text('days_or_units3')->nullable();
			$table->text('epsdt_family_plan3')->nullable();
			$table->text('id_qua3')->nullable();
			$table->text('rendering_provider_id3')->nullable();
			$table->text('service_date4_from')->nullable();
			$table->text('service_date4_to')->nullable();
			$table->text('place_of_service4')->nullable();
			$table->text('emg4')->nullable();
			$table->text('cpt_hcpcs4')->nullable();
			$table->text('modifier4_1')->nullable();
			$table->text('modifier4_2')->nullable();
			$table->text('modifier4_3')->nullable();
			$table->text('modifier4_4')->nullable();
			$table->text('diagnosis_pointer4')->nullable();
			$table->text('s_charges4_1')->nullable();
			$table->text('s_charges4_2')->nullable();
			$table->text('days_or_units4')->nullable();
			$table->text('epsdt_family_plan4')->nullable();
			$table->text('id_qua4')->nullable();
			$table->text('rendering_provider_id4')->nullable();
			$table->text('service_date5_from')->nullable();
			$table->text('service_date5_to')->nullable();
			$table->text('place_of_service5')->nullable();
			$table->text('emg5')->nullable();
			$table->text('cpt_hcpcs5')->nullable();
			$table->text('modifier5_1')->nullable();
			$table->text('modifier5_2')->nullable();
			$table->text('modifier5_3')->nullable();
			$table->text('modifier5_4')->nullable();
			$table->text('diagnosis_pointer5')->nullable();
			$table->text('s_charges5_1')->nullable();
			$table->text('s_charges5_2')->nullable();
			$table->text('days_or_units5')->nullable();
			$table->text('epsdt_family_plan5')->nullable();
			$table->text('id_qua5')->nullable();
			$table->text('rendering_provider_id5')->nullable();
			$table->text('service_date6_from')->nullable();
			$table->text('service_date6_to')->nullable();
			$table->text('place_of_service6')->nullable();
			$table->text('emg6')->nullable();
			$table->text('cpt_hcpcs6')->nullable();
			$table->text('modifier6_1')->nullable();
			$table->text('modifier6_2')->nullable();
			$table->text('modifier6_3')->nullable();
			$table->text('modifier6_4')->nullable();
			$table->text('diagnosis_pointer6')->nullable();
			$table->text('s_charges6_1')->nullable();
			$table->text('s_charges6_2')->nullable();
			$table->text('days_or_units6')->nullable();
			$table->text('epsdt_family_plan6')->nullable();
			$table->text('id_qua6')->nullable();
			$table->text('rendering_provider_id6')->nullable();
			$table->text('federal_tax_id_number')->nullable();
			$table->text('ssn')->nullable();
			$table->text('ein')->nullable();
			$table->text('patient_account_no')->nullable();
			$table->text('accept_assignment')->nullable();
			$table->text('total_charge')->nullable();
			$table->text('amount_paid')->nullable();
			$table->text('balance_due')->nullable();
			$table->text('signature_physician')->nullable();
			$table->text('physician_signed_date')->nullable();
			$table->text('service_facility_info_name')->nullable();
			$table->text('service_facility_info_address')->nullable();
			$table->text('service_facility_info_city')->nullable();
			$table->text('service_info_a')->nullable();
			$table->text('service_info_dd')->nullable();
			$table->text('service_info_b_other')->nullable();
			$table->text('billing_provider_phone_code')->nullable();
			$table->string('billing_provider_phone')->nullable();
			$table->string('billing_provider_name')->nullable();
			$table->string('billing_provider_address')->nullable();
			$table->string('billing_provider_city')->nullable();
			$table->string('billing_provider_a')->nullable();
			$table->string('billing_provider_dd')->nullable();
			$table->string('billing_provider_b_other')->nullable();
			$table->integer('userid')->default(0);
			$table->integer('docid')->default(0);
			$table->integer('status')->default(0);
			$table->tinyInteger('card');
			$table->string('ip_address', 50)->nullable();
			$table->text('dispute_reason')->nullable();
			$table->text('sec_dispute_reason')->nullable();
			$table->text('reject_reason')->nullable();
			$table->string('primary_fdf', 100)->nullable();
			$table->string('secondary_fdf', 100)->nullable();
			$table->integer('producer')->nullable();
			$table->dateTime('mailed_date')->nullable();
			$table->text('eligible_response')->nullable();
			$table->string('p_m_eligible_payer_id', 20)->nullable();
			$table->string('p_m_eligible_payer_name', 200)->nullable();
			$table->dateTime('sec_mailed_date')->nullable();
			$table->tinyInteger('other_insurance_type')->nullable();
			$table->string('patient_relation_other_insured')->nullable();
			$table->integer('p_m_billing_id')->nullable();
			$table->tinyInteger('p_m_dss_file')->nullable();
			$table->integer('s_m_billing_id')->nullable();
			$table->tinyInteger('s_m_dss_file')->nullable();
			$table->string('other_insured_address', 100)->nullable();
			$table->string('other_insured_city', 100)->nullable();
			$table->string('other_insured_state', 100)->nullable();
			$table->string('other_insured_zip', 100)->nullable();
			$table->string('eligible_token')->nullable();
			$table->dateTime('percase_date')->nullable();
			$table->string('percase_name', 100)->nullable();
			$table->decimal('percase_amount', 11, 2)->nullable();
			$table->tinyInteger('percase_status')->default(0);
			$table->integer('percase_invoice')->nullable();
			$table->integer('primary_claim_id')->nullable();
			$table->tinyInteger('fo_paid_viewed')->default(0);
			$table->tinyInteger('bo_paid_viewed')->default(0);
			$table->tinyInteger('closed_by_office_type')->nullable();
			$table->string('s_m_eligible_payer_id', 20)->nullable();
			$table->string('s_m_eligible_payer_name', 200)->nullable();
			$table->string('other_insured_id_number')->nullable();
			$table->tinyInteger('primary_claim_version')->default(2);
			$table->tinyInteger('secondary_claim_version')->default(2);
			$table->string('nucc_8a')->nullable();
			$table->string('nucc_8b')->nullable();
			$table->string('nucc_9a')->nullable();
			$table->string('nucc_9b')->nullable();
			$table->string('nucc_9c')->nullable();
			$table->string('nucc_10d')->nullable();
			$table->string('nucc_30')->nullable();
			$table->string('claim_codes')->nullable();
			$table->string('other_claim_id')->nullable();
			$table->tinyInteger('icd_ind')->nullable();
			$table->string('name_referring_provider_qualifier', 25)->nullable();
			$table->string('diagnosis_a', 25)->nullable();
			$table->string('diagnosis_b', 25)->nullable();
			$table->string('diagnosis_c', 25)->nullable();
			$table->string('diagnosis_d', 25)->nullable();
			$table->string('diagnosis_e', 25)->nullable();
			$table->string('diagnosis_f', 25)->nullable();
			$table->string('diagnosis_g', 25)->nullable();
			$table->string('diagnosis_h', 25)->nullable();
			$table->string('diagnosis_i', 25)->nullable();
			$table->string('diagnosis_j', 25)->nullable();
			$table->string('diagnosis_k', 25)->nullable();
			$table->string('diagnosis_l', 25)->nullable();
			$table->string('current_qual', 25)->nullable();
			$table->string('same_illness_qual', 25)->nullable();
			$table->string('resubmission_code', 25)->nullable();
			$table->tinyInteger('resubmission_code_fill')->nullable();

			$table->timestamps();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('dental_insurance');
	}

}
