<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDentalSummaryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('dental_summary', function(Blueprint $table)
        {
            $table->increments('summaryid');

            $table->integer('formid')->nullable();
            $table->integer('patientid')->nullable();
            $table->string('patient_name')->nullable();
            $table->string('patient_dob')->nullable();
            $table->string('docpcp');
            $table->string('docsmd');
            $table->string('docomd1');
            $table->string('docomd2');
            $table->string('docdds');
            $table->string('osite');
            $table->string('referral_source')->nullable();
            $table->text('reason_seeking_tx')->nullable();
            $table->text('symptoms_osa')->nullable();
            $table->text('bed_time_partner')->nullable();
            $table->text('snoring')->nullable();
            $table->text('apnea')->nullable();
            $table->text('history_surgery')->nullable();
            $table->string('tried_cpap')->nullable();
            $table->integer('cpap_totalnights');
            $table->string('fna')->default('na');
            $table->text('cpap_date')->nullable();
            $table->text('problem_cpap')->nullable();
            $table->text('wearing_cpap')->nullable();
            $table->text('max_translation_from')->nullable();
            $table->text('max_translation_to')->nullable();
            $table->text('max_translation_equal')->nullable();
            $table->string('initial_device_titration_1')->nullable();
            $table->string('initial_device_titration_equal_h')->nullable();
            $table->string('initial_device_titration_equal_v');
            $table->string('optimum_echovision_ver')->nullable();
            $table->string('optimum_echovision_hor')->nullable();
            $table->string('type_device')->nullable();
            $table->text('personal')->nullable();
            $table->string('lab_name')->nullable();
            $table->text('sti_test_1')->nullable();
            $table->text('sti_test_2')->nullable();
            $table->text('sti_test_3')->nullable();
            $table->text('sti_test_4')->nullable();
            $table->text('sti_date_1')->nullable();
            $table->text('sti_date_2')->nullable();
            $table->text('sti_date_3')->nullable();
            $table->text('sti_date_4')->nullable();
            $table->text('sti_ahi_1')->nullable();
            $table->text('sti_ahi_2')->nullable();
            $table->text('sti_ahi_3')->nullable();
            $table->text('sti_ahi_4')->nullable();
            $table->text('sti_rdi_1')->nullable();
            $table->text('sti_rdi_2')->nullable();
            $table->text('sti_rdi_3')->nullable();
            $table->text('sti_rdi_4')->nullable();
            $table->text('sti_supine_ahi_1')->nullable();
            $table->text('sti_supine_ahi_2')->nullable();
            $table->text('sti_supine_ahi_3')->nullable();
            $table->text('sti_supine_ahi_4')->nullable();
            $table->text('sti_supine_rdi_1')->nullable();
            $table->text('sti_supine_rdi_2')->nullable();
            $table->text('sti_supine_rdi_3')->nullable();
            $table->text('sti_supine_rdi_4')->nullable();
            $table->text('sti_lsat_1')->nullable();
            $table->text('sti_lsat_2')->nullable();
            $table->text('sti_lsat_3')->nullable();
            $table->text('sti_lsat_4')->nullable();
            $table->text('sti_titration_1')->nullable();
            $table->text('sti_titration_2')->nullable();
            $table->text('sti_titration_3')->nullable();
            $table->text('sti_titration_4')->nullable();
            $table->text('sti_cpap_p_1')->nullable();
            $table->text('sti_cpap_p_2')->nullable();
            $table->text('sti_cpap_p_3')->nullable();
            $table->text('sti_cpap_p_4')->nullable();
            $table->text('sti_apnea_1')->nullable();
            $table->text('sti_apnea_2')->nullable();
            $table->text('sti_apnea_3')->nullable();
            $table->text('sti_apnea_4')->nullable();
            $table->text('ep_date_1')->nullable();
            $table->text('ep_date_2')->nullable();
            $table->text('ep_date_3')->nullable();
            $table->text('ep_date_4')->nullable();
            $table->text('ep_date_5')->nullable();
            $table->text('dset1');
            $table->text('dset2');
            $table->text('dset3');
            $table->text('dset4');
            $table->text('dset5');
            $table->text('ep_e_1')->nullable();
            $table->text('ep_e_2')->nullable();
            $table->text('ep_e_3')->nullable();
            $table->text('ep_e_4')->nullable();
            $table->text('ep_e_5')->nullable();
            $table->text('ep_s_1')->nullable();
            $table->text('ep_s_2')->nullable();
            $table->text('ep_s_3')->nullable();
            $table->text('ep_s_4')->nullable();
            $table->text('ep_s_5')->nullable();
            $table->text('ep_w_1')->nullable();
            $table->text('ep_w_2')->nullable();
            $table->text('ep_w_3')->nullable();
            $table->text('ep_w_4')->nullable();
            $table->text('ep_w_5')->nullable();
            $table->text('ep_a_1')->nullable();
            $table->text('ep_a_2')->nullable();
            $table->text('ep_a_3')->nullable();
            $table->text('ep_a_4')->nullable();
            $table->text('ep_a_5')->nullable();
            $table->text('ep_el_1')->nullable();
            $table->text('ep_el_2')->nullable();
            $table->text('ep_el_3')->nullable();
            $table->text('ep_el_4')->nullable();
            $table->text('ep_el_5')->nullable();
            $table->text('ep_h_1')->nullable();
            $table->text('ep_h_2')->nullable();
            $table->text('ep_h_3')->nullable();
            $table->text('ep_h_4')->nullable();
            $table->text('ep_h_5')->nullable();
            $table->text('ep_r_1')->nullable();
            $table->text('ep_r_2')->nullable();
            $table->text('ep_r_3')->nullable();
            $table->text('ep_r_4')->nullable();
            $table->text('ep_r_5')->nullable();
            $table->text('mini_consult')->nullable();
            $table->text('exam_impressions')->nullable();
            $table->text('oa_soap')->nullable();
            $table->string('fm_blue')->nullable();
            $table->text('oa_check_1')->nullable();
            $table->text('oa_check_2')->nullable();
            $table->text('oa_check_3')->nullable();
            $table->text('oa_check_4')->nullable();
            $table->text('oa_check_5')->nullable();
            $table->text('oa_check_6')->nullable();
            $table->text('month_check_1')->nullable();
            $table->text('month_check_2')->nullable();
            $table->text('month_check_3')->nullable();
            $table->text('month_check_4')->nullable();
            $table->text('oa_psg')->nullable();
            $table->text('year_check_1')->nullable();
            $table->text('year_check_2')->nullable();
            $table->text('year_check_3')->nullable();
            $table->text('year_check_4')->nullable();
            $table->string('additional_notes')->nullable();
            $table->integer('userid')->nullable();
            $table->integer('docid')->nullable();
            $table->integer('status')->default(1);
            $table->string('ip_address', 50)->nullable();
            $table->string('office')->nullable();
            $table->string('sleep_same_room')->nullable();
            $table->string('currently_wearing')->nullable();
            $table->string('what_percentage')->nullable();
            $table->string('how_long')->nullable();
            $table->text('sleep_md')->nullable();
            $table->string('test_type_name')->nullable();
            $table->text('sti_sleep_efficiency_1')->nullable();
            $table->text('sti_sleep_efficiency_2')->nullable();
            $table->text('sti_sleep_efficiency_3')->nullable();
            $table->text('sti_sleep_efficiency_4')->nullable();
            $table->string('sti_rem_ahi_1')->nullable();
            $table->string('sti_rem_ahi_2')->nullable();
            $table->string('sti_rem_ahi_3')->nullable();
            $table->string('sti_rem_ahi_4')->nullable();
            $table->string('sti_o2_1')->nullable();
            $table->string('sti_o2_2')->nullable();
            $table->string('sti_o2_3')->nullable();
            $table->string('sti_o2_4')->nullable();
            $table->string('sti_other_1')->nullable();
            $table->string('sti_other_2')->nullable();
            $table->string('sti_other_3')->nullable();
            $table->string('sti_other_4')->nullable();
            $table->string('ep_ts_1')->nullable();
            $table->string('ep_ts_2')->nullable();
            $table->string('ep_ts_3')->nullable();
            $table->string('ep_ts_4')->nullable();
            $table->string('ep_ts_5')->nullable();
            $table->string('ep_tr_1')->nullable();
            $table->string('ep_tr_2')->nullable();
            $table->string('ep_tr_3')->nullable();
            $table->string('ep_tr_4')->nullable();
            $table->string('ep_tr_5')->nullable();
            $table->string('appt_notes_1');
            $table->string('appt_notes_2');
            $table->string('appt_notes_3');
            $table->string('appt_notes_4');
            $table->string('appt_notes_1p3');
            $table->string('appt_notes_2p3');
            $table->string('appt_notes_3p3');
            $table->string('appt_notes_4p3');
            $table->string('appt_notes_5p3');
            $table->string('wapn1');
            $table->string('wapn2');
            $table->string('wapn3');
            $table->string('wapn4');
            $table->string('wapn5');
            $table->text('patientphoto');
            $table->string('sleep_qual1');
            $table->string('sleep_qual2');
            $table->string('sleep_qual3');
            $table->string('sleep_qual4');
            $table->string('sleep_qual5');
            $table->integer('location')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('dental_summary');
    }
}
