UPDATE dental_letter_templates SET name = 'Intro Ltr To MD from DSSFLLC' WHERE id = 1;
UPDATE dental_letter_templates SET name = 'Intro Ltr to MD from Franchisee' WHERE id = 2;
UPDATE dental_letter_templates SET name = 'Intro Ltr To DSS Pt of Record' WHERE id = 3;
UPDATE dental_letter_templates SET name = 'Welcome Ltr EMail' WHERE id = 5;
UPDATE dental_letter_templates SET name = 'Welcome Ltr Mail' WHERE id = 6;
UPDATE dental_letter_templates SET name = 'TY MD Referral Pt Not Candidate' WHERE id = 7;
UPDATE dental_letter_templates SET name = 'To Pt Did Not Accept Treatment' WHERE id = 8;
UPDATE dental_letter_templates SET name = 'TY MD Referral' WHERE id = 9;
UPDATE dental_letter_templates SET name = 'TY MD Referral Pt Waiting On' WHERE id = 10;
UPDATE dental_letter_templates SET template = 'dss_referral_thank_you_pt_did_not_accept.php', name = 'TY MD Referral Pt Did Not Accept Treatment' WHERE id = 11;
UPDATE dental_letter_templates SET name = 'TY MD Referral Pt Did Not Come In' WHERE id = 12;
UPDATE dental_letter_templates SET name = 'To MD Mutual Pt Plan to Treat' WHERE id = 13;
UPDATE dental_letter_templates SET name = 'Progress Note to MD and Pt Non Compliance' WHERE id = 17;
UPDATE dental_letter_templates SET name = 'Progress Note to Pt Non Compliance' WHERE id = 18;
UPDATE dental_letter_templates SET name = 'Ltr To MD and Pt after HST' WHERE id = 19;
UPDATE dental_letter_templates SET name = 'To Pt Annual Follow Up' WHERE id = 21;
UPDATE dental_letter_templates SET name = 'Thirty Month Follow Up' WHERE id = 23;
