INSERT INTO dental_letter_templates VALUES ('7', 'Pat. Not a Candidate', '/manage/dss_referral_thank_you_pt_not_candidate.php');
INSERT INTO dental_letter_templates VALUES ('8', 'Pat. did not Accept Treatment', '/manage/dss_to_pt_no_treatment.php');
INSERT INTO dental_letter_templates VALUES ('24', 'Thank you Pat. Referral', '/manage/dss_to_pt_thank_you_pt_referral.php');
INSERT INTO dental_letter_templates VALUES ('6', 'Welcome Letter', '/manage/dss_welcome.php');
UPDATE dental_letter_templates SET name = 'Welcome Letter Email', template = '/manage/dss_welcome_email.php' WHERE id = '5';
INSERT INTO dental_letter_templates VALUES ('13', 'Mutual Patient Plan to Treat', '/manage/dss_referral_treating_mutual_patient.php');
INSERT INTO dental_letter_templates VALUES ('10', 'Pat. Waiting On', '/manage/dss_referral_thank_you_pt_waiting_on.php');
INSERT INTO dental_letter_templates VALUES ('25', 'Pat. Termination', '/manage/dss_to_pt_termination.php');
INSERT INTO dental_letter_templates VALUES ('3', 'Intro letter to DSS Pat.', '/manage/dss_to_pt_intro.php');
INSERT INTO dental_letter_templates VALUES ('19', 'Treatment Complete', '/manage/dss_to_md_pt_treatment_complete.php');
