<?php

namespace DentalSleepSolutions\Http\Requests;

class TmjClinicalExam extends Request
{
    protected $rules = [
        'formid'                   => 'integer',
        'palpationid'              => 'string',
        'palpationRid'             => 'string',
        'additional_paragraph_pal' => 'string',
        'joint_exam'               => 'string',
        'jointid'                  => 'string',
        'jointid_stages'           => 'string',
        'i_opening_from'           => 'string',
        'i_opening_to'             => 'string',
        'i_opening_equal'          => 'string',
        'protrusion_from'          => 'numeric',
        'protrusion_to'            => 'numeric',
        'protrusion_equal'         => 'numeric',
        'l_lateral_from'           => 'string',
        'l_lateral_to'             => 'string',
        'l_lateral_equal'          => 'string',
        'r_lateral_from'           => 'string',
        'r_lateral_to'             => 'string',
        'r_lateral_equal'          => 'string',
        'deviation_from'           => 'string',
        'deviation_to'             => 'string',
        'deviation_equal'          => 'string',
        'deflection_from'          => 'string',
        'deflection_to'            => 'string',
        'deflection_equal'         => 'string',
        'range_normal'             => 'string',
        'normal'                   => 'string',
        'other_range_motion'       => 'string',
        'additional_paragraph_rm'  => 'string',
        'screening_aware'          => 'string',
        'screening_normal'         => 'string',
        'status'                   => 'integer',
        'deviation_r_l'            => 'string',
        'deflection_r_l'           => 'string',
        'dentaldevice'             => 'integer',
        'dentaldevice_date'        => 'date',
        'initial_device_titration_1'       => 'sometimes|numeric',
        'initial_device_titration_equal_h' => 'sometimes|numeric',
        'initial_device_titration_equal_v' => 'sometimes|numeric',
        'optimum_echovision_ver'           => 'sometimes|numeric',
        'optimum_echovision_hor'           => 'sometimes|numeric',
    ];
}
