<?php namespace Ds3\Libraries\Legacy; ?>
<h3>SAAS AGREEMENT</h3>

<h4>DENTAL SLEEP SOLUTIONS FRANCHISING LLC</h4><h4>SOFTWARE AS A SERVICE AGREEMENT </h4><p>THIS IS A LEGALLY  BINDING AGREEMENT between Dental Sleep Solutions Franchising, LLC, a Florida  Corporation (&quot;we&quot; or &quot;us&quot;) and you, as a user of our  on-line health record and patient management system (the &quot;System&quot;).  The term &quot;You&quot; or &quot;you&quot; means the individual or entity who  is using the Service under this Agreement. BY CLICKING &quot;CREATE  ACCOUNT&quot; OR THROUGH THE CONTINUED USE OF THE SYSTEM, YOU ARE UNDERTAKI NG  LEGAL OBLIGATIONS AND CONFERRING LEGAL RIGHTS. Please read this agreement  carefully, and do not click &quot;Create Account&quot; or continue use of the  System unless you agree fully with its terms. You and we are collectively  referred to as the &quot;Parties.&quot;</p>
<p><br />
  This Software as a Service  Agreement (the &quot;Agreement&quot;) is a legal agreement between you and  Dental Sleep Solutions Franchising LLC, a Florida limited liability company  (&quot;Provider&quot;), governing your use of the Dental Sleep Solutions  Practice Manager software (the Software&quot;) as a hosted solution via  Provider's web site (www.dentalsleepsolutions.com) (the &quot;Service&quot;).  The term &quot;You&quot; or &quot;you&quot; means the individual or entity who  is using the Service under this Agreement. The term &quot;use&quot; means accessing,  displaying, executing, loading or otherwise using the Service.</p>
<p><br />
  <strong>Service License</strong>. You are granted a nonexclusive,  nontransferable, revocable, limited license to use the Service for your  internal business purposes in accordance with this Agreement during the Term.</p>
<p><br />
  <strong>Scope of License</strong>. This Agreement grants you up to ten (10) user  accounts that will allow you to use the Service. Fees paid under this agreement  are non-refundable, except as provided in this Agreement or when required by law.  One (1) account, defined as the &ldquo;Provider of Record&rdquo; will have administrative  permissions, which will provide the user the ability to make global changes,  such as password management and ledger/financial correction. One (1) &ldquo;Provider  of Record&rdquo; account is permitted per license (where &ldquo;Provider of Record&rdquo; is an account  utilizing an individual NPI or other differentiating insurance identifiers for  the purpose of allowing a person to document and/or bill patient procedures). Up  to nine (9) other accounts will have general use (non-administrative, non-&ldquo;Provider  of Record&rdquo;) permissions. Each member of your authorized workforce who accesses  Provider&rsquo;s services must have a unique identifier.  You will ensure that under no circumstances credentials  for one member will be used or assigned to another member.  Additional &quot;Provider of Record&quot; or  non-administrative accounts are subject to additional fees, as determined by  Provider.  <br />
  The &ldquo;Provider of Record&rdquo;  is a party to this Agreement for all purposes. Although a member of a &ldquo;Provider  of Record&rsquo;s&rdquo; authorized workforce may have created the initial account or  electronically entered into this Agreement, or may continue to administer administrative  duties on the &ldquo;Provider of Record&rsquo;s&rdquo; behalf, only the &ldquo;Provider of Record&rdquo; is  entitled to any of the rights, remedies or benefits under this Agreement and  control over the administrative rights of the account. The &ldquo;Provider of Record&rdquo;  is likewise subject to all of the covenants, restrictions, limitations,  representations, warranties, waivers and releases included in this Agreement.  The &ldquo;Provider of Record&rdquo; may delegate administrative rights and duties to one  or more members of the &ldquo;Provider of Record&rsquo;s&rdquo; authorized workforce, but the &ldquo;Provider  of Record&rdquo; remains responsible for all activity occurring thereunder.</p>
<p><br />
  <strong>Equipment</strong>. You are responsible for and must provide all equipment, software  (other than any software provided by Provider) and services necessary to use  the Service. The Software may currently be accessed by any modern browser.  However, at some point in the future, Provider may elect to provide you with a  custom browser to be installed on your computer in order to access the Software  (the &quot;Custom Browser&quot;), for purposes of enhancing Software security.  You agree to promptly install any such Custom Browser on behalf of all users  hereunder.</p>
<p><br />
  <strong>Privacy</strong>. Provider will not sell, exchange, or release any confidential  patient information you upload to the Service to a third party without your  express permission, unless required by law or court or governmental order;  provided that Provider may disclose such information to a third party to the  extent necessary to perform Provider&rsquo;s obligations under this Agreement (as  defined below) (e.g. sending patient information to an insurer in connection  with an insurance claim). Provider may contact you regarding account status and  other matters relevant to the underlying Service and/or any use your  confidential information, including without limitation your patient treatment  data statistics, for purposes of making suggestions and recommendations to you  in connection with your performance. Both you and Provider agree to adhere to  data security standards of the Health Insurance Portability and Accountability  Act of 1996 (&quot;HIPAA&quot;).</p>
<p><br />
  <strong>Compliance with Law</strong>. You are solely responsible for ensuring that  your use of the Services in the Agreement comply with applicable law, including  laws relating to the maintenance of the privacy, security, and confidentiality  of patient and other health information. You will not grant any user, including  members of your authorized workforce, any rights to access or use Services  under this Agreement that would not be permitted under applicable laws. Provider  offers no assurance that your use of the Services under the terms of this  Agreement will not violate any law or regulation applicable to you. Except as  otherwise provided in this Agreement, Provider will keep Your information  private and will not share it with third parties, unless we believe in good  faith that disclosure of Your information is necessary to (i) comply with a  court order, warrant or other legal process, (ii) protect the rights, property  or safety of Provider or others, (iii) investigate or enforce suspected  breaches of this Agreement, or (iv) allow our third-party partners to comply  with their obligations under federal or state law.</p>
<p><br />
  <strong>Endorsements</strong>. All product and service marks contained on or associated with  the Service that are not Provider marks are the trademarks of their respective  owners. References to any names, marks, products or services of third parties  or hypertext links to third party sites or information do not necessarily  constitute or imply Provider's endorsement, sponsorship or recommendation of  the third party, information, product or service.</p>
<p><br />
  <strong>Ownership</strong>. You acknowledge and agree that the Provider company names and  logos and all related product and service names, design marks and slogans  (collectively, the &quot;Marks&quot;), and the Service, including all  underlying software or other intellectual property are the property of  Provider, its affiliates or its third party suppliers, as applicable. You are  not authorized to use any of the Marks in any advertising, publicity or any other  commercial manner without the prior written consent of Provider. Your use of  the Service confers no title or ownership in the Service, Software, Materials  (as defined below) or Marks and is not a sale of any rights in the Service,  Software, Materials or Marks. All copyright, patent, trademark, trade secret  and other intellectual property rights in the Software, Service, Materials and  Marks remain in Provider or its third party suppliers, as the case may be.</p>
<p><br />
  <strong>Usage Restrictions</strong>. You warrant that you will not access or use  the Service in any unlawful manner, for any unlawful purpose or in violation of  these terms and conditions or applicable laws, rules and regulations. You agree  that you will be responsible for all usage of the Service through your account,  whether or not authorized by you.<br />
  Except to the extent  permitted above, you may not: permit other individuals to use the Service;  modify, translate, reverse engineer, decompile, disassemble, or create  derivative works based on any product, service, information, content, software,  message, advertisement or any other work found at, aggregated at, contained on,  distributed through, linked to or from, downloaded to or from or in any other  manner accessed from the Service, including without limitation any Custom  Browser (the &quot;Materials&quot;); copy (including copying onto a bulletin  board or similar system) the Service or Materials other than as specified  herein; rent, lease, grant a security interest in, or otherwise transfer rights  to the Service or Materials or remove any proprietary notices or labels on the  Service and Materials. With regard to any Materials in which Provider or any  affiliate or third party supplier of Provider claims a proprietary interest and  which are offered for downloading from the Service, you may download one copy  of such Materials on any single computer for your personal or internal business  use, provided you keep intact all copyright and other proprietary notices.</p>
<p><br />
  <strong>Your Risks</strong>. Provider acts solely as an operator of the Service for your  convenience, and use of the Service and any reliance by you upon any Materials,  including any action taken by you because of such use or reliance, is at your  sole risk. Neither Provider nor any of its underlying suppliers, service  providers, business partners, licensors, employees, distributors or agents is  responsible or liable for, or makes any representations or warranties as  to:&nbsp;</p>
<ul>
  <li>Any representations, promises, recommendations  or inducements that may be made by or through any party (including vendors)  found at, on, through or from the Service;</li>
  <li>The timeliness, accuracy, reliability,  completeness, legality, copyright compliance or decency of the Service or any  Materials;&nbsp;</li>
  <li>Any inaccuracy, omission, error or delay in the  Service or any Materials;&nbsp;</li>
  <li>Nonperformance of or interruption in the Service  or any Materials due to: (i) any act or omission by any disseminating party,  (ii) any force majeure (i.e., flood; riot; labor dispute; accident; action of  government; communications, transmissions or power failure; equipment, systems  or software malfunctions) or any other cause beyond the control of any  disseminating party or (iii) outages, transmission quality or malfunctions of  telephone circuits or computer systems including but not limited to any defects  or failures with respect to your software, computer systems or Internet access  provider;</li>
  <li>The quality of the Service or any Materials  (including the results to be obtained from use of them); or&nbsp;</li>
  <li>Any loss resulting from, arising out of or  related to your access and/or use of or interaction with the Service or the  Materials.</li>
</ul>
<p><strong>Remedies</strong>. Your sole and exclusive remedy for any material failure or  nonperformance of the Software shall be for Provider to use commercially  reasonable efforts to adjust or repair the Software within a reasonable period  of time, as determined by Provider.</p>
<p><br />
  <strong>LIMITATIONS OF LIABILITY</strong>. TO THE MAXIMUM EXTENT PERMITTED BY LAW, UNDER  NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, TORT, CONTRACT, OR OTHERWISE, SHALL  Provider or any of its underlying SUPPLIERS, service providers, BUSINESS  PARTNERS, information providers, licensors, employees, distributors or agents  BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY MONEY DAMAGES, WHETHER DIRECT, INDIRECT,  SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES, EVEN IF Provider  or any of its underlying SUPPLIERS, service providers, BUSINESS PARTNERS,  information providers, licensors, employees, distributors or agents SHALL HAVE  BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER  PARTY. IN THE EVENT THAT NOTWITHSTANDING THE FOREGOING, Provider or any of its  underlying SUPPLIERS, service providers, BUSINESS PARTNERS, information  providers, licensors, employees, distributors or agents IS FOUND LIABLE TO YOU  FOR DAMAGES FROM ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION  (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR  OTHERWISE), the AGGREGATE LIABILITY OF SUCH PARTIES WILL BE LIMITED TO THE  AMOUNT YOU PAID FOR THE SERVICE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION  OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND  EXCLUSION MAY NOT APPLY TO YOU.<br />
  <strong>DISCLAIMER</strong>. EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SOFTWARE, SERVICE AND  MATERIALS ARE PROVIDED &quot;AS IS&quot;, AND PROVIDER HEREBY DISCLAIMS ALL  WARRANTIES AND REPRESENTATIONS, EITHER EXPRESSED OR IMPLIED, WITH RESPECT TO  THE SERVICE OR THE SOFTWARE, ITS QUALITY, PERFORMANCE, MERCHANTABILITY, FITNESS  FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT.</p>
<p><br />
  <strong>Indemnification by You</strong>. You shall indemnify and hold harmless Provider  and any of its underlying suppliers, service providers, business partners,  information providers, licensors, employees, distributors or agents from and  against any and all claims, demands, actions, causes of action, suits,  proceedings, losses, damages, costs, and expenses, including reasonable attorney&rsquo;s  fees, arising from or relating to your use of the Service, or any act, error,  or omission of you or any user of your account in connection therewith,  including, but not limited to, matters relating to incorrect, incomplete, or  misleading data or information; libel; invasion of privacy; infringement of a  copyright, trade name, trademark, service mark, or other intellectual property;  any defective product or any injury or damage to person or property caused by  any products sold or otherwise distributed through or in connection with the  Service; or violation of any applicable law.</p>
<p><br />
  <strong>Term and Termination</strong>. The term of this Agreement (the  &quot;Term&quot;) shall be commensurate with the term of the Initial Agreement  between you and Provider, as such Agreement may be extended from time to time  in accordance with its terms. Your Agreement will be billed on a recurring,  periodic basis. Unless otherwise notified in writing, should Initial Agreement  expire it is assumed that you wish to continue Service with Provider. In order  to provide uninterrupted service, Provider will extend Service on a  month-to-month basis at the then-current market rate until you 1) renew service  with Provider via a new Agreement or 2) notify Provider in writing that you  wish to terminate services. Notwithstanding the foregoing, Provider may  terminate this Agreement immediately, with or without notice, if you breach any  of the provisions of this Agreement, or if Provider is unable to continue  service for reasons outside Provider&rsquo;s control. Upon any such termination, you  must discontinue all use of the Service, uninstall any Custom Browser, and  immediately destroy the Materials together with all copies. The provisions of  this Agreement (other than your right to use the Service) shall survive  termination or expiration of this Agreement.</p>
<p><br />
  <strong>Cancellation</strong>. The duration of your Agreement will be specified in your  contract with Provider.  In the event you  wish to prematurely terminate your Agreement, you may do so by notifying  Provider in writing of your request to prematurely terminate your Agreement at  least 10 (ten) business days before the requested cancellation date.  Agreements that are prematurely terminated  will be subject to the following early termination fees and conditions: 1) $200  administrative processing fee 2) immediate payment to Provider of 75% of the remaining  Agreement balance (calculated as the total Agreement value less monies already  paid) and 3) You must sign Provider&rsquo;s Mutual Termination Agreement.  After these conditions are met Provider will  terminate your service.</p>
<p><br />
  <strong>Export Controls</strong>. None of the Service or underlying information  or technology may be downloaded or otherwise exported or reexported (i) into  (or to a national or resident of) Cuba, Iraq, Libya, Sudan, North Korea, Iran,  Syria or any other country to which the U.S. has embargoed goods; or (ii) to  anyone on the U.S. Treasury Department's list of Specially Designated Nationals  or the U.S. Commerce Department's Table of Denial Orders. By using the Service,  you are agreeing to the foregoing and you are representing and warranting that  you are not located in, under the control of, or a national or resident of any  such country or on any such list. In addition, you are responsible for  complying with any local laws in your jurisdiction which may impact your right  to import, export or use the Service, and you represent that you have complied  with any regulations or registration procedures required by applicable law to  make this license enforceable.</p>
<strong>General</strong>. This Agreement constitutes the entire  agreement between you and Provider with reference to this transaction. This  Agreement will be governed by the laws of the State of Florida, except for that  body dealing with conflicts of law. In the event of any dispute involving this  Agreement, Provider and you each consent to exclusive jurisdiction and venue in  either the state or federal courts in the State of Florida and agree that the  prevailing party shall be entitled to its reasonable attorney fees and costs.  In the event any provision of this Agreement shall be deemed unenforceable,  void or invalid, such provision shall be modified so as to make it valid and  enforceable, and as so modified the entire Agreement shall remain in full force  and effect. No decision, action or inaction by Provider shall be construed to  be a waiver of any rights or remedies available to it. This Agreement, and all  rights and obligations of Provider hereunder, may be assigned by Provider in  connection with any sale to a third party of the Software or Provider's business  to which the Software relates.
