
<h3>SAAS AGREEMENT</h3>

<h4>DENTAL SLEEP SOLUTIONS FRANCHISING LLC</h4><h4>SOFTWARE AS A SERVICE AGREEMENT </h4><p>THIS IS A LEGALLY BINDING AGREEMENT between Dental Sleep Solutions Franchising, LLC, a Florida Corporation ("we" or "us") and you, as a user of our on-line health record and patient management system (the "System").   The term "You" or "you" means the individual or entity who is using the Service under this Agreement.  BY CLICKING "CREATE ACCOUNT" OR THROUGH THE CONTINUED USE OF THE SYSTEM, YOU ARE UNDERTAKI
NG LEGAL OBLIGATIONS AND CONFERRING LEGAL RIGHTS.  Please read this agreement carefully, and do not click "Create Account" or continue use of the System unless you agree fully with its terms.  You and we are collectively referred to as the "Parties."</p>        <p>This Software as a Service Agreement (the "Agreement") is a legal agreement between you and Dental Sleep Solutions Franchising LLC, a Florida limited liability company ("Provider"), governing your
 use of the Dental Sleep Solutions Practice Manager software (the Software") as a hosted solution via Provider's web site (www.dentalsleepsolutions.com) (the "Service"). The term "You" or "you" means the individual or entity who is using the Service under this Agreement.  The term "use" means accessing, displaying, executing, loading or otherwise using the Service. </p>
        <p>Service License.  You are granted a nonexclusive, nontransferable, revocable, limited license to use the Service for your internal business purposes in accordance with this Agreement during the Term.</p>        <p>Scope of License.  This Agreement grants you up to ten (10) user accounts that will allow you to use the Service.  One (1) account will have administrative permissions, which will provide the user
 the ability to make global changes, such as password management and ledger/financial correction.  Up to nine (9) other accounts will have general use (non-administrative) permissions.  Any additional users are subject to additional fees, as determined by Provider.</p><p>Equipment.  You are responsible for and must provide all equipment, software (other than any software provided by Provider) and services necessary to use the Service.  The Software may currently be access
ed by any modern browser.  However, at some point in the future, Provider may elect to provide you with a custom browser to be installed on your computer in order to access the Software (the "Custom Browser"), for purposes of enhancing Software security.  You agree to promptly install any such Custom Browser on behalf of all users hereunder.</p><p>Privacy.  Provider will not sell, exchange, or release any confidential patient information you upload to the Service to a third party without your express permission, unless required by law or court or governmental order; provided that Provider may disclose such information to a third party to the extent necessary to perform Provider’s obligations under this Agreement and the Franchise Agreement (as defined below) (e.g. sending patient information to an insurer in connection with an insurance claim). Provider may contact you regarding account status and other matters relevant to the underlying Service and/or m
ay use your confidential information, including without limitation your patient treatment data statistics, for purposes of making suggestions and recommendations to you in connection with the relationship contemplated under the Franchise Agreement.  Both you and Provider agree to adhere to data security standards of the Health Insurance Portability and Accountability Act of 1996 ("HIPAA").</p><p>Endorsements.  All product and service marks contained on or associated with the Service that are not Provider marks are the trademarks of their respective owners. References to any names, marks, products
 or services of third parties or hypertext links to third party sites or information do not necessarily constitute or imply Provider's endorsement, sponsorship or recommendation of the third party, information, product or service. </p>        <p>Ownership.  You acknowledge and agree that the Provider company names and logos and all related product and service names, design marks and slogans (collectively, the "Marks"), and the Service, including all underlying software or other intellectual property are the property of Provider, its affiliates or its third party suppliers, as applicable.  You are not authorized to use any of the Marks in any advertising, publicity or any other commercial manner without the prior written consent of Provider, except as expressly set forth in the Franchise Agreement. Your use of the Service confers no title or own
ership in the Service, Software, Materials (as defined below) or Marks and is not a sale of any rights in the Service, Software, Materials or Marks.  All copyright, patent, trademark, trade secret and other intellectual property rights in the Software, Service, Materials and Marks remain in Provider or its third party suppliers, as the case may be.</p>
        <p>Usage Restrictions. You warrant that you will not access or use the Service in any unlawful manner, for any unlawful purpose or in violation of these terms and conditions or applicable laws, rules and regulations.  You agree that you will be responsible for all usage of the Service through your account, whether or not authorized by you.</p><p>Except to the extent permitted above, you may not: permit other individuals to use the Service; modify, translate, reverse engineer, decompile, disassemble, or create derivative works based on any product, service, information, content, software, message, advertisement or any other work found at, aggregated at, contained on, distributed through, linked to or from, downloaded to or from or in any other manner accessed from the Service, including without limitation any Custom Browser (the "Materials"); copy (including copying onto a bulletin board or similar system) the Service or Materials other than as specified herein; rent, lease, grant a security interest in, or otherwise transfer rights to the Service or Materials or remove any proprietary notices or labels on the Service and Materials. With regard to any Mate
rials in which Provider or any affiliate or third party supplier of Provider claims a proprietary interest and which are offered for downloading from the Service, you may download one copy of such Materials on any single computer for your personal or internal business use, provided you keep intact all copyright and other proprietary notices. </p><p>Your Risks.  Provider acts solely as an operator of the Service for your convenience, and use of the Service and any reliance by you upon any Materials, including any action taken by you because of such u
se or reliance, is at your sole risk.  Neither Provider nor any of its underlying suppliers, service providers, business partners, licensors, employees, distributors or agents is responsible or liable for, o
r makes any representations or warranties as to: <br />
A.      Any representations, promises, recommendations or inducements that may be made by or through any party (including vendors) found at, on, through or from the Service;<br />
B.      The timeliness, accuracy, reliability, completeness, legality, copyright compliance or decency of the Service or any Materials; <br />C.      Any inaccuracy, omission, error or delay in the Service or any Materials; <br />
D.      Nonperformance of or interruption in the Service or any Materials due to: (i) any act or omission by any disseminating party, (ii) any force majeure (i.e., flood; riot; labor dispute; accident; action of government; communications, transmissions or power failure; equipment, systems or software malfunctions) or any other cause beyond the control of any disseminating party or (iii) outages, transmission quality or malfunctions of telephone circuits or computer systems including but not limited to any defects or failures with respect to your software, computer systems or Internet access provider;<br />
E.      The quality of the Service or any Materials (including the results to be obtained from use of them); or <br />
F.      Any loss resulting from, arising out of or related to your access and/or use of or interaction with the Service or the Materials.</p>
<p>Remedies.  Your sole and exclusive remedy for any material failure or nonperformance of the Software shall be for Provider to use commercially reasonable efforts to adjust or repair the Software within a reasonable period of time, as determined by Provider.</p>
<p>LIMITATIONS OF LIABILITY.  TO THE MAXIMUM EXTENT PERMITTED BY LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, TORT, CONTRACT, OR OTHERWISE, SHALL Provider or any of its underlying SUPPLIERS, service providers, BUSINESS PARTNERS, information providers, licensors, employees, distributors or agents BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY MONEY DAMAGES, WHETHER DIRECT, INDIRECT, SPECIAL, INCIDENTAL, COVER, RELIANCE OR CONSEQUENTIAL DAMAGES, EVEN IF Provider or any of its underlying SUPPLIERS, service providers, BUSINESS PARTNERS, information providers, licensors, employees, distributors or agents SHALL HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY.  IN THE EVENT THAT NOTWITHSTANDING THE FOREGOING, Provider or any of its underlying SUPPLIERS, service providers, BUSINESS PARTNERS, information providers, licensors, employees, distributors or agents IS FOUND LIABLE TO YOU FOR DAMAGES FROM ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE), the AGGREGATE LIABILITY OF SUCH PARTIES WILL BE LIMITED TO THE AMOUNT YOU PAID FOR THE SERVICE.  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT APPLY TO YOU. </p>
<p>DISCLAIMER.  EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SOFTWARE, SERVICE AND MATERIALS ARE PROVIDED "AS IS", AND PROVIDER HEREBY DISCLAIMS ALL WARRANTIES AND REPRESENTATIONS, EITHER EXPRESSED OR IMPLIED, WITH RESPECT TO THE SERVICE OR THE SOFTWARE, ITS QUALITY, PERFORMANCE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT.</p>
<p>Indemnification by You.  You shall indemnify and hold harmless Provider and any of its underlying suppliers, service providers, business partners, information providers, licensors, employees, distributors or agents from and against any and all claims, demands, actions, causes of action, suits, proceedings, losses, damages, costs, and expenses, including reasonable attorneys fees, arising from or relating to your use of the Service, or any act, error, or omission of you or any user of your account in connection therewith, including, but not limited to, matters relating to incorrect, incomplete, or misleading data or information; libel; invasion of privacy; infringement of a copyright, trade name, trademark, service mark, or other intellectual property; any defective product or any injury or damage to person or property caused by any products sold or otherwise distributed through or in connection with the Service; or violation of any applicable law.</p>
<p>Term and Termination.  The term of this Agreement (the "Term") shall be commensurate with the term of the Franchise Agreement between you and Provider, as such Agreement may be extended from time to time in accordance with its terms (the "Franchise Agreement").  Any expiration or termination of the Franchise Agreement for any reason shall automatically terminate this Agreement.  Notwithstanding the foregoing, Provider may terminate this Agreement immediately, with or without notice, if you breach any of the provisions of this Agreement.  Upon any such termination or expiration, you must discontinue all use of the Service, uninstall any Custom Browser, and immediately destroy the Materials together with all copies.  The provisions of this Agreement (other than your right to use the Service) shall survive termination or expiration of this Agreement. </p>
        <p>Export Controls.  None of the Service or underlying information or technology may be downloaded or otherwise exported or reexported (i) into (or to a national or resident of) Cuba, Iraq, Libya, Sudan, North Korea, Iran, Syria or any other country to which the U.S. has embargoed goods; or (ii) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Table of Denial Orders. By using the Service, you are agreeing to the foregoing and you are representing and warranting that you are not located in, under the control of, or a national or resident of any such country or on any such list. In addition, you are responsible for complying with any local laws in your jurisdiction which may impact your right to import, export or use the Service, and you represent that you have complied with any regulations or registration procedures required by applicable law to make this license enforceable. </p>
        <p>General.  This Agreement constitutes the entire agreement between you and Provider with reference to this transaction.  This Agreement will be governed by the laws of the State of Florida, except for that body dealing with conflicts of law. In the event of any dispute involving this Agreement, Provider and you each consent to exclusive jurisdiction and venue in either the state or federal courts in the State of Florida and agree that the prevailing party shall be entitled to its reasonable attorney fees and costs.  In the event any provision of this Agreement shall be deemed unenforceable, void or invalid, such provision shall be modified so as to make it valid and enforceable, and as so modified the entire Agreement shall remain in full force and effect.  No decision, action or inaction by Provider shall be construed to be a waiver of any rights or remedies available to it.  This Agreement, and all rights and obligations of Provider hereunder, may be assigned by Provider in connection with any sale to a third party of the Software or Provider's business to which the Software relates.</p>
