
<h3>HIPAA AGREEMENT</h3>
<h4>Dental Sleep Solutions Franchising, LLC, User Agreement</h4>
<p>(Effective January 1, 2013)</p>
<p>THIS IS A LEGALLY BINDING AGREEMENT between Dental Sleep Solutions Franchising, LLC, a Florida Corporation ("we" or "us") and you, as a user of our on-line health record and patient management system (the "System").   The term "You" or "you" means the individual or entity who is using the Service under this Agreement.  BY CLICKING "CREATE ACCOUNT" OR THROUGH THE CONTINUED USE OF THE SYSTEM, YOU ARE UNDERTAKING LEGAL OBLIGATIONS AND CONFERRING LEGAL RIGHTS.  Please read this agreement carefully, and do not click "Create Account" or continue use of the System unless you agree fully with its terms.  You and we are collectively referred to as the "Parties."</p>
<p>THIS HIPAA PRIVACY COMPLIANCE AGREEMENT (hereinafter known as "Agreement") is made between YOU (hereinafter known as "Covered Entity") and DENTAL SLEEP SOLUTIONS FRANCHISING LLC, a Limited Liability Company, organized under the laws of the State of Florida (hereinafter known as "Business Associate"). Covered Entity and Business Associate shall collectively be known herein as "the Parties."</p>
<p>WHEREAS, Covered Entity is a health care provider whose activities are generally described as a Dental Practice;</p>
<p>WHEREAS, Business Associate is in the business of providing services to dental industry and its activities are generally described as Office Administration Support Services for the treatment of Snoring and Obstructive Sleep Apnea using Orthotic Appliance Therapy;</p>
<p>WHEREAS, Covered Entity wishes to commence a business relationship with Business Associate that shall be memorialized in a separate Franchise Agreement of even date herewith; and</p>
<p>WHEREAS, the nature of the prospective contractual relationship between Covered Entity and Business Associate may involve the exchange of Protected Health Information ("PHI") as that term is defined under the Health Insurance Portability and Accountability Act of 1996 ("HIPAA") as amended by Health Information Technology for Economic and Clinical Health Act of 2009 ("HITECH Act"), including all pertinent regulations issued by the Department of Health and Human Services ("HHS").</p>
<p>NOW, THEREFORE, the premises having been considered and with acknowledgment of the mutual promises and of other good and valuable consideration herein contained, the Parties, intending to be legally bound, hereby agree as follows:<br />
A. Definitions.<br />
1. Breach. "Breach" has the same meaning as this term has in §13400 of Health Information Technology for Economic and Clinical Health Act of 2009 ("HITECH Act").<br />
2. Business Associate. "Business Associate" shall mean DENTAL SLEEP SOLUTIONS FRANCHISING LLC.<br />
3. Covered Entity. "Covered Entity" shall mean YOU.<br />
4. Designated Record Set. "Designated Record Set" has the same meaning as this term has in 45 CFR §164.501.<br />
5. Individual. "Individual" has the same meaning as this term has in 45 CFR §164.501.<br />
6. Privacy Rule. "Privacy Rule" shall mean the Standards for Privacy of Individually Identifiable Health Information at 45 CFR Part 160 and Part 164, Subparts A and E., as amended by the HITECH Act.<br />
7. Protected Health Information. "Protected Health Information" (or "PHI") has the same meaning as this term has in 45 CFR §160.103 (as amended by the HITECH Act), limited to the information created or received by Business Associate from or on behalf of Covered Entity.<br />
8. Required By Law. "Required By Law" has the same meaning as this term has in 45 CFR §164.501.<br />
9. Secretary. "Secretary" shall mean the Secretary of the U.S. Department of Health and Human Services or his designate.<br />
10. Security Standards. "Security Standards" means the security standards for protection of PHI promulgated by the Secretary in Title 45 C.F.R.<br />
11. Unsecured Protected Health Information. "Unsecured Protected Health Information" shall mean Protected Health Information (PHI) that is not secured through the use of a technology or methodology specified by the Secretary in regulations or as otherwise defined in the §13402(h) of the HITECH Act.<br />
12. Any prospective amendment to the laws referenced in this definitional section prospectively amend this agreement to incorporate said changes by Congressional act or by regulation of the Secretary of HHS.<br />
B. Obligations and Activities of Business Associate.<br />
1. Business Associate agrees to not use or disclose Protected Health Information other than as permitted or required by the Agreement or as Required By Law.<br />
2. Business Associate agrees to employ administrative, physical, and technical safeguards meeting required Security Standards for business associates as Required By Law to prevent disclosure or use of PHI other than as allowed by this Agreement.<br />
3. Business Associate agrees to mitigate, to the extent practicable, any harmful effect that is known to Business Associate of a use or disclosure of PHI held by Business Associate in violation of the requirements of this Agreement.<br />
4. Business Associate agrees to report to Covered Entity any use or disclosure of the Protected Health Information not provided for by this Agreement of which it becomes aware.<br />
5. If a breach of unsecured protected health information occurs at or by Business Associate, the Business Associate must notify Covered Entity following the discovery of the breach without unreasonable delay and, in all cases, no later than sixty (60) days from the discovery of the breach. To the extent possible, the Business Associate should provide the Covered Entity with the identification of each individual affected by the breach as well as any information required to be provided by the Covered Entity in its notification to affected individuals. Business Associates shall comply with all regulations issued by HHS and applicable state agencies regarding breach notification to Covered Entity.<br />
6. Business Associate agrees to ensure that any agent, including a subcontractor, to whom it provides Protected Health Information received from, or created or received by Business Associate on behalf of Covered Entity agrees to the same restrictions and conditions that apply through this Agreement to Business Associate with respect to PHI.<br />
7. Business Associate agrees, at the request of Covered Entity, to provide Covered Entity (or a designate of Covered Entity) access to Protected Health Information in a Designated Record Set in prompt commercially reasonable manner in order to meet the requirements under 45 CFR §164.524.<br />
8. Business Associate agrees to make any amendment(s) to Protected Health Information in a Designated Record Set that the Covered Entity directs or agrees to pursuant to 45 CFR §164.526 at the request of Covered Entity or an Individual, in a prompt and commercially reasonable manner.<br />
9. Business Associate agrees to make internal practices, books, and records, including policies and procedures for safeguarding Protected Health Information, relating to the use and disclosure of Protected Health Information received from, or created or received by Business Associate on  behalf of, Covered Entity available to the Covered Entity, or to the Secretary (including official representatives of the Secretary), in a prompt commercially reasonable manner for purposes of determining Covered Entity's compliance with the Privacy Rule.<br />
10. Business Associate shall, upon request with reasonable notice, provide Covered Entity access to its premises for a review and demonstration of its internal practices and procedures for safeguarding PHI.<br />
11. Business Associate agrees to document such disclosures of Protected Health Information and information related to such disclosures as would be required for Covered Entity to respond to a request by an Individual for an accounting of disclosures of Protected Health Information in accordance with 45 CFR §164.528.<br />
12. Business Associate agrees to provide to Covered Entity or an Individual, in a prompt commercially reasonable manner, information collected in accordance with this Agreement, to permit Covered Entity to respond to a request by an Individual for an accounting of disclosures of Protected Health Information in accordance with 45 CFR §164.528.<br />
C. Permitted Uses and Disclosures by Business Associate.<br />
Except as otherwise limited in this Agreement, Business Associate may use or disclose Protected Health Information, as follows:<br />
1. On behalf of, Covered Entity, provided that such use or disclosure would not violate the Privacy Rule if done by Covered Entity.<br />
2. Except as otherwise limited in this Agreement, Business Associate may disclose Protected Health Information for the proper management and administration of the Business Associate, provided that disclosures are required by law, or Business Associate obtains reasonable assurances from the person to whom the information is disclosed that it will remain confidential and used or further disclosed only as required by law or for the purpose for which it was disclosed to the person, and the person notifies the Business Associate of any instances of which it is aware in which the confidentiality of the information has been breached.<br />
D. Obligations of Covered Entity.<br />
1. Covered Entity shall notify Business Associate of any limitation(s) in its notice of privacy practices of Covered Entity in accordance with 45 CFR §164.520, to the extent that such limitation may affect Business Associate's use or disclosure of Protected Health Information.<br />
2. Covered Entity shall notify Business Associate of any changes in, or revocation of, permission by Individual to use or disclose Protected Health Information, to the extent that such changes may affect Business Associate's use or disclosure of Protected Health Information.<br />
3. Covered Entity shall notify Business Associate of any restriction to the use or disclosure of Protected Health Information that Covered Entity has agreed to in accordance with 45 CFR §164.522, to the extent that such restriction may affect Business Associate's use or disclosure of Protected Health Information.<br />
4. Covered Entity shall not request Business Associate to use or disclose Protected Health Information in any manner that would not be permissible under the Privacy Rule if done by Covered  Entity. Nothing in this paragraph shall restrict the ability of Business Associate to use or disclose PHI as set forth in paragraph C.2. herein.<br />
E. Remedies in Event of Breach. <br />
Business Associate hereby recognizes that irreparable harm will result to Covered Entity, and to the business of Covered Entity, in the event of breach by Business Associate of any of the covenants and assurances contained in Paragraphs B or C of this agreement. As such, in the event of breach of any of the covenants and assurances contained in paragraphs B or C above, Covered Entity shall be entitled to enjoin and restrain Business Associate from any continued violation of Paragraphs B or C. Furthermore, in the event of breach of Paragraphs B or C by Business Associate, Covered Entity shall be entitled to reimbursement and indemnification from Business Associate for the Covered Entity's reasonable attorneys’ fees and expenses and costs that were reasonably incurred as a proximate result of the Business Associate's breach. The remedies contained in this paragraph E shall be in addition to (and not supersede) any action for damages and/or any other remedy Principal may have for breach of any part of this Agreement.<br />
F. Term and Termination.<br />
1. Term of Agreement. The Term of this Agreement shall be effective as of the date given at the top of Page 1 herein, and shall terminate when all of the Protected Health Information provided by Covered Entity to Business Associate, or created or received by Business Associate on behalf of Covered Entity, is destroyed or returned to Covered Entity, or, if it is infeasible to return or destroy Protected Health Information, protections are extended to such information, in accordance with the termination provisions in this Section.<br />
2. Termination for Cause. Upon Covered Entity's knowledge of a material breach by Business Associate, Covered Entity shall either:<br />
        a. Provide an opportunity for Business Associate to cure the breach or end the violation and terminate this Agreement if Business Associate does not cure the breach or end the violation within the time specified by Covered Entity;<br />
        b. Immediately terminate this Agreement if Business Associate has breached a material term of this Agreement and cure is not possible; or<br />
        c. If neither termination nor cure are feasible, Covered Entity shall report the violation to the Secretary.<br />
3. Effect of Termination.<br />
        a. Except as provided in paragraph E.3(b) of this section, upon termination of this Agreement, for any reason, Business Associate shall return or destroy all Protected Health Information received fro
m Covered Entity, or created or received by Business Associate on behalf of Covered Entity. This provision shall apply to Protected Health Information that is in the possession of subcontractors or agents of Business Associate. Business Associate shall retain no copies of the Protected Health Information.<br />        b. In the event that Business Associate determines that returning or destroying the Protected Health Information is infeasible, Business Associate shall provide to Covered Entity notification of the 
conditions that make return or destruction infeasible. Upon notification to Covered Entity that return or destruction of Protected Health Information is infeasible, Business Associate shall extend the protec
tions of this Agreement to such Protected Health Information and limit further uses and disclosures of such Protected Health Information to those purposes that make the return or destruction infeasible, for 
so long as Business Associate maintains such Protected Health Information.<br />
G. Miscellaneous Terms.<br />
        1. State Law. If state law applicable to the relationship between Business Associate and Covered Entity contains additional or more stringent requirements than federal law for Business Associates reg
arding any aspect of PHI privacy, then Business Associate agrees to comply with the higher standard contained in applicable state law.<br />
        2. Consideration. Business Associate recognizes that the promises it has made in this Agreement shall, henceforth, be detrimentally relied upon by Covered Entity in choosing to continue or commence a
 business relationship with Business Associate.<br />
3. Modification. This Agreement may only be modified through a writing signed by the Parties and, thus, no oral modification hereof shall be permitted. The Parties agree to take such action as is necessary t
o amend this Agreement from time to time as is necessary for Covered Entity to comply with the requirements of the Privacy Rule and the Health Insurance Portability and Accountability Act of 1996, as amended
.<br />
4. Notice to Covered Entity. Any notice required under this Agreement to be given Covered Entity shall be made via electronic communication based on the email address YOU provide.<br />
5. Notice to Business Associate. Any notice required under this Agreement to be given Business
Associate shall be made in writing to:<br />
Dental Sleep Solutions Franchising LLC, 3090 East Bay Drive, Suite 205, Holmes Beach, Florida 34217<br />

